### PR TITLE
LPS-47199

### PR DESCRIPTION
**Pull request by arbetts**
this pull depends on source formatter changes here:

https://github.com/jonathanmccann/liferay-portal/pull/733

otherwise the source formatter will remove the constructor for the private inner class in CustomSQLTest

### CODE REVIEW

**Comment by arbetts** [comment]
@juliocamarero 

the tests were working in my local environment

(except the source formatter which i described in my other comment)

is there something wrong with the SQL?

**Comment by arbetts** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27276. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
