### PR TITLE
Control menu new mark up and styles

### PR DESCRIPTION
**Pull request by pat270**
Hey @juliocamarero, I got the control-menu to look like the mock up in desktop. Mobile still needs work, but I wanted to make sure this was good with you before I spent more time on it. I couldn't find a ticket for this task, but I can reword the commits if we have one.

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pat270** [comment]
Resent with these changes at https://github.com/juliocamarero/liferay-portal/pull/3918.

**Pull request closed without merging**
