### PR TITLE
[TECHNICAL-SUPPORT] LPS-69258

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @juliocamarero,

I'm not quite sure about this issue so I wanted to get your feedback on it. In LPS-47775, an onClick method is now added to all actions that are post methods. It determines whether or not a method is post by checking for "p_p_lifecycle=0" in it's URL. Due to it treating post methods as submitting a form, we are unable to open a link in a new tab.

For the fix I went ahead and simply added "p_p_lifecycle=0" to the end of the URLs, but I had a couple of questions:

1. Is the "p_p_lifecycle=0" check robust enough to differentiate between get and post methods?

2. Should we even bother fixing this issue or should we say the new behavior is that the link opens in the current window due to SPA?

Thanks for looking at this.

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
@jbalsas do we have another way to fix this? can we ignore spa in these links?

**Comment by juliocamarero** [comment]
Hey @jonathanmccann 

could you please confirm if this is related to SPA somehow? @jbalsas just told me that SPA should automatically ignore any link with target blank....

**Comment by jonathanmccann** [comment]
@juliocamarero I don't believe it has to do with SPA since the URL is changed from a hyperlink to an onClick event due to the IconTag and LPS-47775. With my changes, the URL remains a hyperlink and will leverage the target blank attribute. Please let me know if I misunderstood though.

**Comment by jbalsas** [comment]
Hey @jonathanmccann, I was taking a look, and your diagnostic is correct, but the fix is rather obscure. We need to figure out why the url is being changed and prevent it in a more straightforward way.

**Comment by jbalsas** [comment]
For instance, wouldn't it be easier to simply set the `method` attribute to `get`?

**Comment by jbalsas** [comment]
On top of that, I'd say that we might want to add the condition that if `target == _blank`, then we might not want `forcePost` to be `true`...

**Comment by jonathanmccann** [comment]
@jbalsas That makes a lot of sense. That was part of what I wanted to figure out by pushing this fix up. Whether or not the backend logic was at fault. I can work on putting a new fix together that incorporates that logic.

**Comment by jonathanmccann** [comment]
https://github.com/juliocamarero/liferay-portal/pull/4318

**Pull request closed without merging**
