### PR TITLE
LPS-56836

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
At https://github.com/jorgediaz-lr/liferay-portal/commit/5ee128b1edfc3b3d2d413a8c045897bfcd4169bf I am changing call to fetchLatestIndexableArticleVersion, to be consistent with rest of JournalArticleIndexer
At https://github.com/jorgediaz-lr/liferay-portal/commit/faf9df478e8580ce882eef3240030c6d360f589e we avoid issues with **doReindex(article, false);** when JOURNAL_ARTICLE_INDEX_ALL_VERSIONS is false
At https://github.com/jorgediaz-lr/liferay-portal/commit/c15e07f1a0e49fb53171fde4bc67aed4eb31a521 I am removing unnecessary code.

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Failed tests seems not be related with JournalArticleIndexer, as it is falling at **liferay-plugins/shared/alloy-mvc-shared/src/com/liferay/alloy/mvc/BaseAlloyControllerImpl**

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
@jcampoy esto cambia algunas de las últimas cosas que hiciste, le puedes echar un ojo?

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28062. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/46bdfe4~1...46bdfe4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
