### PR TITLE
LPS-55229 (better approach)

### PR DESCRIPTION
**Pull request by juangon**
Hi @juliocamarero, I've made some improvements so we don't rely on LocalUtil as it can give false positives when using some locale as beta locale.

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30660. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
