### PR TITLE
[Technical Support] LPS-65410

### PR DESCRIPTION
**Pull request by dustinryerson**
@Preston-Crary 

https://issues.liferay.com/browse/LPS-65410

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39324. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
@dustinryerson @Preston-Crary you included not autogenerated files in the build service commit.

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39325. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/e749cc6~2...e749cc6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
@dustinryerson @Preston-Crary I have moved the file to another commit. 

I have also fixed the semantic versioning. Could you please have a look at my changes?
https://github.com/brianchandotcom/liferay-portal/pull/39325

Everytime you change an API you need to execute "gradle baseline" to see if you need to increase the version of your package. In this situation, you need a module to use the latest api from another module and for this you can use the "default" version.

**Comment by Preston-Crary** [comment]
@juliocamarero Thanks. We have some generated tests (the persistence tests). I'll try to get better with semver.

**Comment by dustinryerson** [comment]
Agreed, thanks very much @juliocamarero!

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39369. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/aa7f1cc~1...aa7f1cc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39591. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/4fcabe3~1...4fcabe3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
