### PR TITLE
LPS-58438

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Julio,

- See my concerns here for this fix: https://github.com/hhuijser/liferay-portal/pull/2465
- Logic to retrieve latest version number is based on the sql we use for JournalArticleFinder.findByExpirationDate

**Comment by yuhai** [comment]
Hi Julio,

I just want to update the pull request. Could you please review the pull request when you have free time? Because the pull request came from EE customer's issue.

Regards,
Hai

**Comment by daledotshan** [comment]
Hey Julio,
Do you have a chance to look at this pull request? if is for a ee customer
Thanks

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30580. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/0e31aa8~1...0e31aa8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
