### PR TITLE
LPS-52728 Structure field types are not sorted correctly in the Asset Publisher

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@juliocamarero This fixes the portal but breaks solr.  I'm currently working on a fix for solr that depends on these changes. I'll be holding off on development of that fix until you've gotten a chance to review these changes.

Thanks!

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/308. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
