### PR TITLE
LPS-68301

### PR DESCRIPTION
**Pull request by eperezg**

### CODE REVIEW

**Comment by eperezg** [comment]
ci:reopen

**Comment by eperezg** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43933. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/f3c6d7f~1...f3c6d7f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43947. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/06f1ab5~1...06f1ab5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eperezg** [comment]
ci:retest

**Comment by eperezg** [comment]
ci:reopen

**Pull request closed without merging**
