### PR TITLE
[TECH-SUPPORT] LPS-54646 Localized URL (ex. /en) are not being mapped accordingly to site available locales

### PR DESCRIPTION
**Pull request by laszlocsontos**
Hi Julio,

This is the continuation of https://github.com/juliocamarero/liferay-portal/pull/3319. I solved your request this way: https://github.com/laszlocsontos/liferay-portal/commit/19a52a194632c3372c4f34fd47f628e5c57f5239.

Please let me know about your thoughts.

Cheers,
László

/CC: @fafonso

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/1148. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @laszlocsontos 

I have sent the first (easy) part to Brian: https://github.com/brianchandotcom/liferay-portal/pull/25769

and the rest to Shuyang: https://github.com/shuyangzhou/liferay-portal/pull/1148

Thanks!!

**Comment by juliocamarero** [comment]
Let me know if you just prefer everything to go together and I can close Brian's.

cheers!

**Comment by laszlocsontos** [comment]
Hey Julio,

I think that this one https://github.com/juliocamarero/liferay-portal/commit/878896f338186e8813bfca5f7788dfac5f845c5a is missing from https://github.com/brianchandotcom/liferay-portal/pull/25769.

Nevertheless you could https://github.com/brianchandotcom/liferay-portal/pull/25769, if @shuyangzhou wants me to change my solution he can just omit the thread-safety related commits and push the logic changes to Brian.

Cheers,
László

**Pull request closed without merging**
