### PR TITLE
LPS-68672

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/42160

Thx.

**Comment by brianchandotcom** [comment]
ci:stop

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42201. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/8fef119~1...8fef119) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
