### PR TITLE
LPS-55267 Extract Sites Admin and Site Settings to OSGI

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26273. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/8e88ef8~1...8e88ef8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
