### PR TITLE
LPS-58917 show actions for site administration and user space portlets in general permissions list

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@brianchiu do you know why this pull is failing? it seems that all the tests passed...

**Comment by brianchiu** [comment]
hey @pavel-savinov 

Yeah, you are right. All the tests that ran passed. I looked at the console and it seems it ran out of memory.
https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/225//console

@kiyoshilee @michaelhashimoto
Can you guys investigate this? I thought the memory issues were more or less solved.

In the meantime I'm going to have it run again.

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
ci:retest

**Comment by brianchiu** [comment]
hey @pavel-savinov

I've re-run it a couple times, and it looks like the remaining failures are inconsistent. However, the out of memory error from the first time the PR tester ran didn't happen again.

JournalArticleSearchTest.testSearchRecentEntries
PortalLogAssertorTest.testScanXmlLog

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30662. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
