### PR TITLE
LPS-44596 semantic versioning

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/13. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/8e277af~5...8e277af) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
