### PR TITLE
[TECHNICAL-SUPPORT] LPS-61666

### PR DESCRIPTION
**Pull request by arbetts**
see https://in.liferay.com/web/support/forums/-/message_boards/view_message/17914641 for discussion

cc @eperezg

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hi @arbetts 

this doesn't belong to WCM team. Could you please send to someone else?

thanks!

**Comment by eperezg** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eperezg** [comment]
Done! see https://github.com/JorgeFerrer/liferay-portal/pull/628

Thank you.

**Pull request closed without merging**
