### PR TITLE
Sass 3.2.5 upgrade

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
@juliocamarero  oops I forgot to add the mac dylib, let me send that in a new commit

**Comment by juliocamarero** [comment]
@gamerson sure! in this same pull?

**Comment by gamerson** [comment]
@juliocamarero  yeah i just pushed a new commit with the mac lib give it a try and let me know.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @gamerson @david-truong

I still have the problem whit these changes.

Right now, the only way for me to have it correctly is using the ruby sass compiler....

**Comment by gamerson** [comment]
What is your OS? Because I didn't add the Linux libraries only the windows/mac are updated.

**Comment by juliocamarero** [comment]
OS X Yosemite (10.10.3)

**Comment by david-truong** [comment]
Are you testing the unit test or the build?

Try the unit test only cause the rest of the build is going to still use
the old version

**Comment by juliocamarero** [comment]
Hi guys, I was testing the build.

The test acutally runs successfully! \o/



 [junit] Running com.liferay.sass.compiler.jni.internal.JniSassCompilerTest
    [junit] Testsuite: com.liferay.sass.compiler.jni.internal.JniSassCompilerTest
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2,599 sec
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2,599 sec
    [junit

 [junit] Running com.liferay.sass.compiler.jni.internal.libsass.LiferaysassLibraryTest
    [junit] Testsuite: com.liferay.sass.compiler.jni.internal.libsass.LiferaysassLibraryTest
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,284 sec
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0,284 sec
    [junit]

**Comment by juliocamarero** [comment]
Closing the pull for now... will you send this to Brian? Let me know if I can help! Thanks a lot!

**Comment by david-truong** [comment]
Hey Greg,

I'm going to send you a pr.  I got the tests working.

Dave

On Thu, Jun 25, 2015 at 10:18 AM, Julio Camarero <notifications@github.com>
wrote:

> Closed #3499 <https://github.com/juliocamarero/liferay-portal/pull/3499>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/juliocamarero/liferay-portal/pull/3499#event-340166949>
> .
>



-- 
David Truong
Product Manager
david.truong@liferay.com
Liferay, Inc

**Pull request closed without merging**
