### PR TITLE
LPS-64071

### PR DESCRIPTION
**Pull request by neilking**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
great job @neilking!! I had that same fix in my mind :)

thanks a lot! :+1:

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/37392. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by neilking** [comment]
It's my honor to have a solution same as you thought :)

**Pull request closed without merging**
