### PR TITLE
LPS-68040 save default value according to site default language instead of portal default language for localized fields.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Comes from https://github.com/lipusz/liferay-portal/pull/143

**Comment by marianoalvarosaiz** [comment]
Hi @juliocamarero, did you have chance to take a look?
Thanks in advance.

**Comment by juliocamarero** [comment]
not yet... I am still catching up... sorry for the delay 😞

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marianoalvarosaiz** [comment]
I've created a new pull with the changes we talked about: https://github.com/juliocamarero/liferay-portal/pull/4286

**Pull request closed without merging**
