### PR TITLE
LPS-68040 system.packages.extra.mf

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
I've added the change to surpass Semantic Versioning.

**Comment by marianoalvarosaiz** [comment]
ci:retest

**Comment by marianoalvarosaiz** [comment]
Hi @juliocamarero,
 did you have chance to take a look at the new semantic versioning change?
Thanks.

**Comment by marianoalvarosaiz** [comment]
Hi @juliocamarero,
 do you have any update on this?
Thanks in advance.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44396. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
