### PR TITLE
LPS-55229 master

### PR DESCRIPTION
**Pull request by juangon**
Hi @juliocamarero. Tests that were asked here: https://github.com/brianchandotcom/liferay-portal/pull/26393#issuecomment-101408897. Will do the same for the backport

### CODE REVIEW

**Comment by juangon** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30572. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/0d2db6c~3...0d2db6c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @juangon 

I have tried to avoid using arrays since they are really confusing and prone to error. I hope I didn't break the test. Could you please review my changes? https://github.com/brianchandotcom/liferay-portal/pull/30572

thank you!

**Pull request closed without merging**
