### PR TITLE
LPS-66570

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-66570

Same pull than https://github.com/juliocamarero/liferay-portal/pull/4176 but I have updated versions in **bnd / gradle / system.packages.extra.mf** files

thanks to @migue

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
Seems that pr is failing because in master we are executing tests of ee-7.0.x modules. (I have tested it in following pr: https://github.com/jorgediaz-lr/liferay-portal-ee/pull/56 )
As I have to change package **com.liferay.portal.kernel.model** version, It is also necessary to change in everywhere we are using that package

So I think the solution of adding a new method to Group it is not possible to implement.

Brian doesn't like to implement GroupImpl.isActive(): https://github.com/brianchandotcom/liferay-portal/pull/40814
Do you have any other idea?

**Comment by jorgediaz-lr** [comment]
@juliocamarero I have rebased my changes to today master

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41701. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/5df2394~2...5df2394) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
