### PR TITLE
LPS-54791 Apply new settings framework in Breadcrumb

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/3364. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
