### PR TITLE
LRQA-24545 Add accceptance test to delete page and assert page tree

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-24545

### CODE REVIEW

**Comment by evannagayama** [comment]
@juliocamarero I created the acceptance test to delete pages + assert them in the page tree. 

It will fail because the bug exists currently (see screen record below). Let me know if you want me to create a ticket for it. 
There are 2 issues:
1. Delete a page in the navigation and it still displays in the tree 
2. Delete the page in the tree  and it still displays in the navigation

pagedelete

**Comment by juliocamarero** [comment]
You are right.

Yesterday we fixed half of it here: https://issues.liferay.com/browse/LPS-64881
I just opened the other bug, I will ping you when that one is fixed too: https://issues.liferay.com/browse/LPS-65164

thanks a lot!! 👍

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39320. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
