### PR TITLE
[TECHNICAL-SUPPORT] LPS-69258

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @jbalsas

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
See brianchandotcom/liferay-portal/pull/45291

**Pull request closed without merging**
