### PR TITLE
LPS-55354 Apply new settings framework in IFrame Module

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26336. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/f3d9431~1...f3d9431) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/11. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/c8bd549~3...c8bd549) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
