### PR TITLE
LPS-58592 Getting double entries for web contents on Asset publisher portlet in staging

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Julio

A new fix for [LPS-58592](https://issues.liferay.com/browse/LPS-58592).

I modified the steps to reproduce in JIRA a little bit to avoid your confusion.

Let me know if you have any concerns

Thanks
John.

### CODE REVIEW

**Comment by zxdgoal** [comment]
@juliocamarero 

Could you help us a bit more about this issue?

Indeed, the second commit is not that reasonable.

Because, via page template, we still can make AP to choose the live group when it is the related staging group.

If we do not stop this, many issues will come alive and my second commit isn't sufficient for fixing them

Thanks

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @zxdgoal 

I like this solution more than the previous one. You are not allowing to use the live group from staging. Why isn't this enough?

**Comment by zxdgoal** [comment]
Hey Julio 

If we decide not allowing AP in a page template to be able to chosse a specific live site as its scoop, then this pr is engough. 

If this is the case, I need include the fix for disabling chossing live site for page template in UI as well. 

Thanks
John

**Comment by juliocamarero** [comment]
Hi @zxdgoal 

after talking to Zsigmond, we decided that from a page Template you can only choose those 3 scopes:
- Current Site
- Current Page 
- Global

would that work for you too?

**Comment by zxdgoal** [comment]
Hey Julio

I am ok with this idea as it can avoid many complex issues integrated with staging. 

One concern in my mind is that we'd better to document this changes clearly so that if anyone realize he cannot not choose a live site in AP form page template in the futur, he will know the reasons

Should I be responsible for developing the fix of diabling choosing live site in UI?

Thanks
John

**Comment by juliocamarero** [comment]
Hey @zxdgoal 

if you can work on it that would be great since we don't have that time right now and we would delay this several weeks.

I agree with the documentation, we just need to mention @codyhoag in our pulls and he will document the changes we are making. (Nothing for you to worry yet, Cody, just testing ;)  

I will close this pull for now.

thanks a lot!

**Pull request closed without merging**
