### PR TITLE
[TECHNICAL-SUPPORT] LPS-47199 User is unable to view owned draft web content in home tab in control panel

### PR DESCRIPTION
**Pull request by moltam89**
Hi Julio,

this is quite an old issue, I was asked to resolve it.

Unfortunately, I couldn't figure it out why this fix was rejected exactly.
That's why I decided to rebase it (I used the original commits as only a few modifications were needed to apply it to the current head) and send id to you again.

Can I use this fix as the pattern, and apply it other places as well.

Could you please recheck this solution?

Thanks,
Tamás

### CODE REVIEW

**Comment by moltam89** [comment]
Hey Julio,

the methods were renamed, and the tests were not modified accordingly.

Actually, the method name changes seems unnecessarily to me, as in later commits the userId parameter vanished.

I can modify the original fix, but first it would be nice to get a confirmation that this is the right approach to handle the issue.

Thanks,
Tamás

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @moltam89 

can you please coordinate with @arbetts? As you can see here, this pull already got to Brian and Brian didn't like it, but he explained to Andrew what he wanted (unfortunately, this happen in person, so we don't know the details of that conversation). 

https://github.com/brianchandotcom/liferay-portal/pull/20975
https://github.com/juliocamarero/liferay-portal/pull/3444#
Andrew has been very busy but he knows what was missing. 

Thanks!

**Comment by moltam89** [comment]
Hey @juliocamarero ,

I contacted @arbetts earlier, basically he mentioned two things:

> Brian wanted me to add this to the CustomSQLUtil just like we have the replace method for other aspects

As far as I can see it's already done by Eudaldo.

>The basic message I received from Brian was to fix it everywhere and not just for web content.

This is missing of course.

Maybe I should ask Brian about this.

Thanks,
Tamás

**Comment by juliocamarero** [comment]
ok, let's try again :)

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26985. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
