### PR TITLE
LPS-57275

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey Julio,

Sending this to you because this is a regression caused by LPS-51775 and you reviewed that one as well...

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zxdgoal** [comment]
It seems that Julio is not available

Sent it to Jon : https://github.com/jonmak08/liferay-portal/pull/1301

**Comment by juliocamarero** [comment]
Hey @hhuijser

this belongs to the Users Administration team now. Can you please send the pull to then? (probably @drewbrokke)

thank you!

**Pull request closed without merging**
