### PR TITLE
LPS-54784 Whether we only reindex latest indexable articles should depend on the value of journal.articles.index.all.versions.

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @zxdgoal 

we don't think this is the right solution since this will create many other issues (such as indexing draft web content articles).

Also, the scheduled web content article shouldn't be found in the Live Site until it is not scheduled anymore.

**Comment by zxdgoal** [comment]
Hey @juliocamarero 

Two more questions: the scheduled articles can be searched in live site after manual reindexing. This looks inconsistent as if we do not allow scheduled articles indexed, the manual reindexing should not help. 
Also, dose JOURNAL_ARTICLE_INDEX_ALL_VERSIONS=true mean indexing one article in all versions with ALL status(including Draft)? If so, the sechduled should be indexed. From the code, when reindexing articles, I do not see if the articles is from staging site or remote site is considered. 

Personally, allowing admin on live searching scheduled articles make sense since they have permission on those articles and normal end user cannot find it as their heads are false. 

Thanks
John.

**Comment by zxdgoal** [comment]
Another thing confused is that from this code

```
	@Override
	protected void doReindex(String className, long classPK) throws Exception {
		JournalArticle article =
			JournalArticleLocalServiceUtil.fetchJournalArticle(classPK);

		if (article == null) {
			article =
				JournalArticleLocalServiceUtil.fetchLatestIndexableArticle(
					classPK);
		}

		if (article != null) {
			doReindex(article);
		}
	}
```
This first time we are trying to fetch journal article with ``fetchJournalArticle(classPK)`` we do not even consider its indexability and status.

But the second time, we are trying fetch journal article with resource primary key, we do consider its indexability and status.

What in my mind is whenever using ``fetchLatestIndexableArticle``, we should consider the value of ``journal.articles.index.all.versions`` 

```
    #
    # Set this to true to index all article versions. Set this to false to index
    # only the last indexable version.
    #
    journal.articles.index.all.versions=true
```

Thanks
John.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25743. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
