### PR TITLE
[TECHNICAL SUPPORT]LPS-54528 Empty RSS feed in Asset Publisher when ordering by custom field of a structure

### PR DESCRIPTION
**Pull request by zsolah**
Hi,

Using the new getAssetEntryResults for generating RSS in dynamic mode.

Please review.

Thanks.

### CODE REVIEW

**Comment by zsolah** [comment]
ci:retest

**Comment by zsolah** [comment]
ci:retest

**Comment by zsolah** [comment]
ci:retest

**Comment by zsolah** [comment]
I have rebased to current master.

**Comment by zsolah** [comment]
ci:retest

**Comment by zsolah** [comment]
ci:retest

**Comment by zsolah** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/zsolah/liferay-portal/pull/5. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/48a3702~1...48a3702) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
