### PR TITLE
LPS-54791 Apply new settings framework in Breadcrumb OSGI Module

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
We need to consider the defualt ddm template key

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
