### PR TITLE
LPS-52763

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/BryanEngler/liferay-portal/pull/40. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/f874cef~4...f874cef) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/BryanEngler/liferay-portal/pull/50. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/2fb3926~7...2fb3926) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
