### PR TITLE
LPS-85458 Support AND and OR Operation in ExpressionVisitor Query Generator

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:stop

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63279. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63280. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/7761ca5a5e40~1...7761ca5a5e40) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
