### PR TITLE
LPS-85270- ExpressionVisitor should return the Search Query

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63058. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/14af687bb0a8~3...14af687bb0a8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63090. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/62923fe87c6e~3...62923fe87c6e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
