### PR TITLE
LPS-52734 SF

### PR DESCRIPTION
**Pull request by sergiogonzalez**
From Hugo:

Hey Sergio,

Sending this one to you as well since it looks like you implemented the localization of friendlyURLs (LPS-34850).
See https://issues.liferay.com/browse/LPP-14490 for some discussion regarding the fix.

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/23510. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hi @yuhai 

I have sent Brian the easy part :) https://github.com/brianchandotcom/liferay-portal/pull/23510

However, for the other part I checked with PM about the new behavior and we don't think this is the best solution since you are making the decision for the user without letting the user know.

Our proposal would be that you use for the new default language, the value from the old default language. (The old default language can be obtained from the other localized fields such as the name or the title using the method layout.getDefaultLanguageId())

Let me know what you think.

Thanks!

**Comment by yuhai** [comment]
Hi Julio,

I reply my idea by email. Please check it in email.

Thanks,
Hai

**Pull request closed without merging**
