### PR TITLE
LPS-63581

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @juliocamarero,

Attached is an update for http://issues.liferay.com/browse/LPS-63581.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
Actaully sending to @ealonso

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/ealonso/liferay-portal/pull/678

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38132. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
