### PR TITLE
[TECHNICAL SUPORT] LPS-57844 - Search Results return Assets in Inactive Site

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-57844

Hi Julio,

Even though it changes the FacetedSearcher, I thought you should also check this before forwarding to André @arboliveira

@jhinkey: Please, resend @9132ab5 if Brian accepts it.

Thx,
Tibor

/cc @adamnagy

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31963. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/arboliveira/liferay-portal/pull/69. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Looks good to me! thanks!

**Pull request closed without merging**
