### PR TITLE
[WAITING FOR ANSWER] LPS-50057 Re-publication of articles triggers classTypeId change after 6.1GA2>6.2 upgrade

### PR DESCRIPTION
**Pull request by IstvanD**
Hey Julio,

This is a fix for a WCM Upgrade issue.

Could you please check it?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hi @IstvanD 

besides the source formatting error mentioned above, I tend to think that when you execute this process, the DDMStructure may not exist yet. You probably need to ensure that your upgrade process executes after the others from Journal and DDM right?

**Comment by IstvanD** [comment]
Hi @juliocamarero 

Thank you for the feedback.

I took care to place UpgradeAsset after UpgradeJournal (since the updateStructure() methods convert JournalStructures to DDMStructures), but besides that, I've been not avare that other upgrade processes need to precede UpgradeAsset.

Do you mean it should be placed after UpgradeDynamicDataMapping too?

Best regards,
István

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/23187. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Got it, I was assuming you were using the alphabetical order. The order has to be alphabetical, see my changes for this type of situations.

**Comment by IstvanD** [comment]
Hi @juliocamarero 

Thank you very much, I have seen your SF and I will implement may changes according to it.

**Pull request closed without merging**
