### PR TITLE
[TECHNICAL-SUPPORT | Jan 19] LPS-52435 Fix SF

### PR DESCRIPTION
**Pull request by lipusz**
I decided not to reorganize, as it doesn't contain any confusing commit imho.

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/23270. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
@lipusz, for the 6.2 backport I would go with the minimal changes (your initial solution) since this new solution is cleaner but could potentially have more consequences.

thanks a lot!

**Comment by lipusz** [comment]
@juliocamarero 

Hi Julio,

Keeping your words in mind, I'd say that the main issue was the missing "doAsGroupId" param from the JSP, so the changes in the ServicePreAction may not be needed for 62x.

I'll test the changes before submitting the backport.

Regards
-tibor

**Comment by lipusz** [comment]
Ok, backported, I needed everything.

**Pull request closed without merging**
