### PR TITLE
LPS-63235 master

### PR DESCRIPTION
**Pull request by juangon**
Hi @juliocamarero. It turns out after https://issues.liferay.com/browse/LPS-57330 (where embedded portlets are checked for cacheability too) all Guest pages were NOT cached, as some of the embedded portlets did not have this option enabled.

Please, can you check that Product navigation user personal bar and product menu web can be enabled without any problem of showing stale data to users? My checks had been successful until now.

@eduardolundgren @marcellustavares I've removed layout cacheability for the DDL/DDM portlets as it wasn't working actually due to this bug, and would show stale data after this fix.

After you finish the work, can you send to @shuyangzhou so he can review the second and third commit?

/cc @adolfopa 

Thanks!

### CODE REVIEW

**Comment by juangon** [comment]
BTW this can make a huge performance improvement for Liferay 7.

**Comment by juangon** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juangon** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/2831. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/1095322~1...1095322) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
