### PR TITLE
[WAITING] LPS-66991 Keep going on getting layouts if we cannot get them from journal url title.

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by zxdgoal** [comment]
Hey Eudaldo, Julio

Usually, we use "/-/" as a special character to append a journal url title.

However, in rare case(but we do allow), we use "-" as a page's friendly url. In this case, the portal will consider the content after "/-/" as a url title to find a layout and of course, it will fail. 

But it will throw an exception and return directly, rather than give another try to look for a layout with page url.

HTH

Thanks
John.

**Comment by daledotshan** [comment]
Hey Julio,
This is for a ee customer, could you help to review this pull request?
Thanks,
Dale

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @daledotshan @zxdgoal 

I just verified that in 6.2 we didn't allow the friendly urls to be just "-".
I think that is the right behaviour and the regression is that somehow we are allowing that in 7.

Could you please have a look at it?

Thanks a lot!

**Comment by zxdgoal** [comment]
Hey Julio

I verified in ee-6.2.x we do allow "/-" as a page url.

The customer has "/-" as page url because some Japanese characters are not able to be used due to LPS-37900

These characters are replaced by "-". so they have to use "/-" as a page url.(They did not deliberately set them)

Thanks
John.

**Comment by juliocamarero** [comment]
Hey @zxdgoal 

I was testing on a database that didn't allow me to change the friendly url to "-" but on a new one it does, there was probably something wrong in my previous one, sorry about that.

Looking at the code we have in other places of the portal, we should never allow a friendly url to be only "-". This case was never considered and it would break many other things in the portal. We should never allow friendly urls to contain any of our "friendly url separators" ("-", "~"... etc)  We probably need to add this logic to the validation of our page friendly urls.

Regarding the situation from your customer, I think we have another bug there. When a user leaves a friendly url empty on purpose, we default to the layoutId (a number such as 1,2... etc). In the situation in which all the characters are invalid and the friendly url has hyphens only, I think we should default to the same thing instead of creating these weird urls.

We can help you with this problem in master if you want. Thanks!

**Comment by zxdgoal** [comment]
Hey Julio

I agree with you that we should  disallow end user using "-" as page url.

For this customer, he did not deliberately use "-" in page url but the portal convert Japanese characters into "-"

I believe we should allow them to use Japanese characters in journal url title and page url. We also have [LPS-65233 ](https://issues.liferay.com/browse/LPS-65233) addressing this feature, it would be great that engineer team could give priority to it.

Thanks
John.

**Comment by juliocamarero** [comment]
Hey @zxdgoal 

> I agree with you that we should disallow end user using "-" as page url.
> 
> For this customer, he did not deliberately use "-" in page url but the portal converted Japanese characters into "-"
> 

I agree with you too. We shouldn't generate those urls either. If not character is valid, we should default to the layoutId, as we do when users set an empty friendlyURL.

> I believe we should allow them to use Japanese characters in journal url title and page url. We also have LPS-65233 addressing this feature, it would be great that engineer team could give priority to it.

I agree too. It's in our todo list, we'll get there in the next months, but I am not sure we will be able to backport this, so we can't use this for solving the current situation.

My proposal is the following:
1. We disallow urls like "-" "~" or that start with "-/" "~/"
2. We never generate those urls ourself (we will default to the layoutId instead of -)
3. We support japanese characters in friendly urls.

1 & 2 should be implemented in master and then backported to 6.2. Could you take care of these? We can help you if you want.
3 we can take care of it, we will fix it for master in the next months (however, I am not sure of the date or if it will be backportable to 6.2)

Does it sound right for you?

Let me close this pull in the meantime, we can continue by email if needed.

thank you!

**Comment by zxdgoal** [comment]
Thank you, Julio.

I will take care of 1 & 2 and keep you updated.

Thanks
John.

**Comment by juliocamarero** [comment]
Hi @zxdgoal 

has there been any progress on this?

thanks a lot!

**Comment by zxdgoal** [comment]
Here you go. https://github.com/juliocamarero/liferay-portal/pull/4220

**Pull request closed without merging**
