### PR TITLE
LPS-64809 - Solved panels by using keyboard

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Hey guys @juliocamarero @jbalsas , this is the faster way to fix the problem with panels by using keyboard:

navegable

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38462. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Yep, I think it is a good idea because this is how it was originally designed. We changed it to support links inside but now they are outside, so I like this :+1:

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/evannagayama/liferay-portal/pull/684. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/7939e86~1...7939e86) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
