### PR TITLE
LPS-67685 Journal Upgrade fails for large titles/descriptions

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:/ @jorgediaz-lr

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42589. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
