### PR TITLE
LPS-66570

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-66570

Previous pull: https://github.com/brianchandotcom/liferay-portal/pull/40814

Instead creating a new `GroupImpl.isActive()` that hides Hibernate method, I am adding a new method in `GroupLocalServiceImpl` called isActive(group)

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
I have rebased to last master

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by jorgediaz-lr** [comment]
rebased to last master

**Comment by jorgediaz-lr** [comment]
rebased to last master

**Comment by jorgediaz-lr** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43741. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
