### PR TITLE
LPS-58592 Source formatting

### PR DESCRIPTION
**Pull request by matethurzo**
Hey Julio,

I think you should review this even though the problem seems to be in staging, but it touches Asset code.

Let me know if I can help!

Thanks,

Máté

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @daviddotzhang @hhuijser 

I tend to think this change is not correct, could you please have a look at my comments?

thanks!

**Comment by daviddotzhang** [comment]
@juliocamarero  @hhuijser  @daledotshan 

"This will make that in a site with staging enabled you can no longer select other sites you can administer or parent sites."

1: we have different ideas on this point, as we have discussed from the forum, we can,t use a liferay site when enable staging.
https://in.liferay.com/web/support/forums/-/message_boards/message/16319823

https://in.liferay.com/web/support/forums/-/message_boards/message/16319823#_19_message_16347682

2:besides, if we enable remote staging, this will lead to can,t find relate site in remote, is this right ?
currently this fix allows to use its own site and Global site.

**Comment by daledotshan** [comment]
Hey @juliocamarero,
Could you please look at David last comment?

**Comment by daledotshan** [comment]
Hey @juliocamarero,
Do you have chance to look at David comment? This issue is for a ee customer, if do think this is not a bug, we will reply to customer. This issue has been open long time. If think it is a issue but the fix is not good, could you give us a direction how should we fix this issue. So far the asset publisher and staging function mix together make some behavior confused

Thanks,
Dale

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hi @daledotshan @daviddotzhang 

the issue described looks like a bug to me. However, this is not the right solution since this is breaking other features. 

Could you please talk to our SME to see if he has some other idea?

thank you!

**Comment by daviddotzhang** [comment]
@daledotshan @juliocamarero 

As the one is a little confusing, I think we can give customer a fast update. whether this is a bug or not.

When Enable staging, in asset publisher -> Configuration-> Scope.
do we allow to use a Live site when clicking "Select" button ?

**Comment by juliocamarero** [comment]
@daviddotzhang 

The way it should work is:

- When the current site is a staging site, you can choose in scope:
    * the current site (staging), global, any page scope, other parent/child/administrable sites (only their live version)

 - When the current site is a live site, you can not configure asset publisher so this should not be a problem.

- When the current site doesn't have staging enabled, you can choose in scope:
 * the current site, global, any page scope, other parent/child/administrable sites (only their live version)

Let me know if you have any question, thanks!

**Comment by zxdgoal** [comment]
Thank you, Julio.

Resent : https://github.com/juliocamarero/liferay-portal/pull/3693

**Pull request closed without merging**
