### PR TITLE
LPS-67718 SF

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Julio,
Could you treat this pull request as high priority as one customer is waiting for this fix?  LPP ticket opened long time
Thanks,
Dale

**Comment by zxdgoal** [comment]
@carloslancha 

Julio seems not available @ealonso could you help review this?

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43494. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
