### PR TITLE
LPS-71094

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yuhai** [comment]
Hi Julio,

Hope you are well.

The issue comes from EE customer. Could you please review this when you have free time?

Regards,
Hai

**Comment by yuhai** [comment]
Hi Julio,

Hope you are well.

I was wondering if you had completed reviewing this PR. The customer is waiting for a fix for resolving the issue.

Regards,
Hai

**Comment by ealonso** [comment]
Hey @yuhai,

I've sent it to Brian: https://github.com/brianchandotcom/liferay-portal/pull/47744. Could you please close this one?

By the way, please use "@" to refer users, because in this way we cannot get the nofications of your comments unless we come here to check the pull request.

Thanks!!
Eudaldo.

**Comment by ealonso** [comment]
ci:close

**Comment by juliocamarero** [comment]
thank you @ealonso !

**Pull request closed without merging**
