### PR TITLE
LPS-60617 - Apply accordion design to the product menu

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-60617

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Wohoooo!!! so awesome!! Great job @pat270 and @marcoscv-work !!! :clap: :clap: :clap:

**Comment by marcoscv-work** [comment]
All the effort by @pat270 ! thanks a lot!

**Comment by juliocamarero** [comment]
Finishing all the fixes to the tests. We will hopefully send this today: https://github.com/anthony-chu/liferay-portal/pull/8#issuecomment-160622469

**Pull request closed without merging**
