### PR TITLE
LPS-55246 Ensure create and modified dates are updated when they should be

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
I updated https://github.com/Preston-Crary/liferay-portal/commit/ca4e428209b5f2c98246f3c0e47aca6fd92e441c to resolve the issues with the tests and amended the commit message to explain the difference.

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hey @Preston-Crary 

7 tests break after your changes. could you please have a look? They seem related to Site Templates propagation. Freel free to ask @epgarcia for help about those.

thanks!

**Pull request closed without merging**
