### PR TITLE
LPS-55949

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by ChrisKian** [comment]
This PR is unrelated to this failed test.  The changes affect portlet preferences, which are rendered on the front end.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26984. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
