### PR TITLE
LPS-62570

### PR DESCRIPTION
**Pull request by Ithildir**
Hi Julio!
@david-truong asked me to send you this pull, which enables libSass 3.3.1. The problem is that, in this branch, the CSS looks broken on Firefox (and Edge), while it's still fine on Chrome.

Do you have any idea on how to solve this?

Thank you!

### CODE REVIEW

**Comment by david-truong** [comment]
i think the issues are these empty url() https://github.com/sass/libsass/pull/1887

**Comment by juliocamarero** [comment]
Hi @david-truong @Ithildir 

I have no idea of how this works or what to do :(

**Comment by david-truong** [comment]
Just build with ant all and open it in Firefox

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35843. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/7479f14~1...7479f14) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
