### PR TITLE
LPS-65233 encode url in test to comform with RFC 3986

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @ealonso

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44916. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
