### PR TITLE
LPS-54974

### PR DESCRIPTION
**Pull request by jcampoy**
Hey Julio, take a look at this fix. Thx!

### CODE REVIEW

**Comment by juliocamarero** [comment]
@jcampoy which problem is causing this? why do you need this change?

**Comment by jcampoy** [comment]
Hi @juliocamarero, take a look at https://issues.liferay.com/browse/LPS-54974

The specif use case is to create a site with pages to model a dictionary using the kind of friendlyURLs described in the ticket.

I don't see any problem in use /c as ends of a friendlyURL. could you confirm that?

Regards.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/25748. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
