### PR TITLE
LPS-56347 regen

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30209. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
