### PR TITLE
[Technical Support] LPS-66808

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @arbetts

Hey @juliocamarero, this is a follow-up pull to the request you made a while ago: https://github.com/dustinryerson/liferay-portal-ee/pull/1988#issuecomment-232926240

I wrote the fix based on the final code from https://github.com/dustinryerson/liferay-portal-ee/pull/1988.

Does this look good to you? If so would you mind pushing it forward?

Thank you in advance!

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42594. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/fe66bb4~1...fe66bb4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
thank you @dustinryerson! I think you missed to actually use the variable in the taglib later :)

Can you please have a look at my changes? thank you!

**Comment by dustinryerson** [comment]
Ahh, good catch. Thanks @juliocamarero!

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42631. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/bfa22d5~1...bfa22d5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
