### PR TITLE
[WAITING for answer] LPS-63437

### PR DESCRIPTION
**Pull request by jkappler**
Hey @jkappler,

Attached is an update for http://issues.liferay.com/browse/LPS-63437.  I sent this to you since you had originally added the CSS classes to this portlet.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @jonmak08 

there isn't any other portlet that needs to add this class. It seems the class is added automatically everywhere else. 

Do you know why it isn't added here? we should probably add it somewhere else in the theme... maybe portal_pop_up.ftl or in the code that opens de dialog? (not sure about it though, just thinking out loud)

**Comment by jonmak08** [comment]
Hey @juliocamarero,

In a normal portlet, it is rendered via portlet.ftl and you can see the ```portlet``` CSS class is added to the ```<section />```  (https://github.com/jonmak08/liferay-portal/blob/master/modules/apps/platform/frontend/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/portlet.ftl#L10).

For the portal_popup.ftl, there is no ```<section />`` tag and and the ```portlet``` CSS is never added because it grabs just the contents of the portlet and puts it in the pop_up window (https://github.com/jonmak08/liferay-portal/blob/master/modules/apps/platform/frontend/frontend-theme/frontend-theme-unstyled/src/main/resources/META-INF/resources/_unstyled/templates/portal_pop_up.ftl).

If you look at the generated markup, you will notice that inside of a the portal_pop_up, the wrapping CSS class is generated from my changes in https://github.com/jkappler/liferay-portal/commit/df502a9d67cdd29fb52d997834c5f6ac630b2a72.

image

The other option is to wrap ```portal_pop_up.ftl``` with a ```<div />``` or ```<section />``` that has the CSS class ```portlet``` too.  Either way I think we have a few options.  I just chose the route that affects the least changes in markup and affects only specifically what we need.

Let me know your thoughts.  I think we should run this by @natecavanugh and @jblasas before it makes it in upstream.

**Comment by juliocamarero** [comment]
Sure, I agree.

I tend to prefer the option to add the <section /> in the portal_pop_up.ftl 

this will prevent us from having to make more changes like this in the future.

Let me know what you think,

thanks a lot!

**Comment by jonmak08** [comment]
Hey @juliocamarero,

Great, I will add the change to the ```portal_pop_up.ftl``` and send that change through.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
You can also close this pull request now since I can send that directly to @natecavanaugh for review.

**Comment by jonmak08** [comment]
Hey @juliocamarero,

I have just tested my changes based on my suggestions and it looks like we have to fix it the way I sent this to you originally.  I forgot to account for the column ```<div />```.  The ```portlet``` CSS class needs to go inside of that ```<div />``` for the alignment to work.  I will have to revisit this issue and send another fix, since this happens in every iframe'd portlet content.

image

Feel free to close this for now.

Please let me know if you have any questions. Thanks!

**Comment by juliocamarero** [comment]
Ok, I will close this pull for now Jon.

I tend to think adding this classes to the portlet is not a good idea since potentially any portlet can be opened in an iframe and this seems just a hack for a common situation.

I can see 2 solutions:
 a) add to portal_pop_up.ftl everything that our css needs
 b) make our css more generic so that it also works for pop ups.

Can you please talk about this to @natecavanaugh?

thanks!!

**Pull request closed without merging**
