### PR TITLE
LPS-61826 - getting roles Id

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @marcellustavares @linolaoj 

This is not fixing the root issue of the problem... I was trying to debug myself and fix it but I can't reproduce the issue :(

Let me explain you the problem: 

The parameter that you seem to receive empty is filled using javascript in the file search_iterator/lexicon/bottom.jspf

	searchContainer.updateDataStore(<%= primaryKeysJSONArray.toString() %>);

If you don't receive the parameter, we should debug and see if the problem is:
 - js code is not updating the input properly
 - java code not giving the right values to that js call

I can help you with the solution if you can reproduce it.

Let me know what you think,

thanks!!

**Comment by marcellustavares** [comment]
@linolaoj, could you double check to see if it's NLR? thanks @juliocamarero

**Comment by linolaoj** [comment]
Hi @marcellustavares  , it is still reproducible, I'll debug and look for another solution.

Thanks!

**Comment by juliocamarero** [comment]
Hey @linolaoj 

can you try after this pull? I was playing with it and I was not able to reproduce it after those changes: https://github.com/brianchandotcom/liferay-portal/pull/34323

**Comment by linolaoj** [comment]
Hi @juliocamarero , it is no longer reproducible after the pull :) 

Thanks!

**Comment by marcellustavares** [comment]
@linolaoj, could you resolve the original ticket as NLR? Also please link the tickets.

Thanks a lot!

**Comment by linolaoj** [comment]
Done :)

**Pull request closed without merging**
