### PR TITLE
LPS-62323 Implement new alert component in trash taglib

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @jbalsas

**Comment by jbalsas** [comment]
LGTM

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34672. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34679. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/d067e83~1...d067e83) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
