### PR TITLE
LPS-56220 Removes old language properties

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27231. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/8419707~1...8419707) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
