### PR TITLE
[TECHNICAL-SUPPORT] LPS-69196 Use permanent redirect only if the locale prefix is availab…

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by moltam89** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/moltam89/liferay-portal/pull/369. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/2716bc3~10...2716bc3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/moltam89/liferay-portal/pull/370. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/8354d99~7...8354d99) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45503. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/06bd158~8...06bd158) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
