### PR TITLE
[TECHNICAL-SUPPORT] LPS-69196 Add option to disable permanent redirect.

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hi Sergio,

I'm sending this pr to you as I can see that you introduced permanent redirecting.

I think usually it's quite OK, but we have a customer who's needs are different, therefore I created new property so they can disable it.

Could you please review my changes?

Thanks,
Tamás

### CODE REVIEW

**Comment by moltam89** [comment]
Hi @juliocamarero ,

do you have any updates?

Thanks,
Tamás

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @moltam89 

I tend to think the main benefit of the permanent redirect is for SEO. Is the customer aware that disabling this would have a negative impact on the SEO of their website? I am not sure we want to make this change. Let me ask our PM for his opinion.

**Comment by moltam89** [comment]
Hi @juliocamarero ,

I wasn't aware of it.

Honestly, I can't really see the connection between permanent redirect and SEO, I'll have to take a deeper look.
Could you please explain it to me in a nutshell?

Thanks for double checking it!
Tamás

**Comment by juliocamarero** [comment]
Sure @moltam89,

Search engines penalize the rank of your site if you have 2 urls pointing to the exact same content (e.g. /home, /casa). In order to avoid that, you can do a permanent redirect from one of them to the other.  https://moz.com/learn/seo/redirection

**Comment by moltam89** [comment]
Hi @juliocamarero ,

thanks for the explanation, it's clearer now for me, though I still have some questions :).

Let's use your example, when I go to **/en/web/guest/casa** I'm going to be redirected to **/home**.
It's OK to use a permanent redirect in this case, as we will be always redirected to the same URL.

However, if I go to **/web/guest/casa without the locale prefix**, the result is not deterministic.
I could be redirected to **/home** again, but if I'm using Hungarian settings, I'm going to be redirected to the Hungarian friendly URL.

Therefore reaching  **/web/guest/casa** could potentially result in several different  redirects, in this case I don't think we should use a permanent redirect.

This is actually what I was trying to fix in the first place:
If I'm using English settings, going to  **/web/guest/casa** will redirect me to  **/home**, and after that even if I'm changing my locale to Spanish, I'll be always redirected to **/home**, which is annoying.

So probably using a property to decide whether we want a permanent redirect or not is not the best option.
Shouldn't we decide instead by checking whether the URL has a locale prefix or not?

Thanks!
Tamás

**Comment by juliocamarero** [comment]
I agree, I think that makes sense 👍  and Jose Ignacio is almost convinced too ;)

Can you please send me a pull with this change?

thank you!

**Comment by moltam89** [comment]
See https://github.com/juliocamarero/liferay-portal/pull/4323,

Thanks!

**Pull request closed without merging**
