### PR TITLE
LPS-85787 FilterProviders can be created from models others than StructuredContent

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63507. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/f139c68d6a2d~1...f139c68d6a2d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/596. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/55513e2ce54f~1...55513e2ce54f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
