### PR TITLE
[Technical Support]LPS-58592 Getting double entries for web contents on Asset publisher portlet in staging

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Julio

This is a a fix for LPS-58592.

See the previous talk: https://github.com/juliocamarero/liferay-portal/pull/3693

One thing I am confused about is how to configure Current Page as AP's scope?

The list only shows:
1. Current site(page template)
2. Global
3. Other site..

I removed Other site.. option for page template and site template simply.

Please help to review it 

Thanks
John.

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32208. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/9f184cb~1...9f184cb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @zxdgoal great job on the pull!! The change was really simple :D

Regarding your question, the page scope logic is just above yours.. you can see this block:

					<c:if test="<%= GroupLocalServiceUtil.getGroupsCount(company.getCompanyId(), Layout.class.getName(), layout.getGroupId()) > 0 %>">


let me know if you think there may be any issue with that.

thanks a lot!

**Comment by zxdgoal** [comment]
I see, thank you.

**Comment by zxdgoal** [comment]
Just one more question. Are we going to merge this into Branch 6.2.X ?

I believe releasing this fix in fix packs could arise potential arguments with our EE customers.

**Comment by juliocamarero** [comment]
That depends on the support team. I am not doing the backport and it won't be done unless someone from support requests it. Feel free to reach Zoltan to ask him about it. thanks!

**Comment by zxdgoal** [comment]
Got it.

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/evannagayama/liferay-portal/pull/252. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
