### PR TITLE
LPS-57562 Support for apps to Display the number notification in the product menu

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32275. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/4de4975~3...4de4975) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32301. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/ff98144~3...ff98144) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
