### PR TITLE
LPS-58674 Organization portrait doesn't display after uploaded a image

### PR DESCRIPTION
**Pull request by pei-jung**
Hi Julio,

The fix I made is based on https://issues.liferay.com/browse/LPS-42864. Let me know if there's any issue. Thanks!

/cc @jorgeferrer @drewbrokke @hhuijser @natecavanaugh

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
That looks great! I totally missed it, thanks a lot @pei-jung !! :+1: 

by the way, I changed the LPS number since it was not the right one ;)

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30665. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pei-jung** [comment]
Oops, my bad. Thanks for catching that, @juliocamarero! :)

**Pull request closed without merging**
