### PR TITLE
LPS-58264

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
This is issue does not happen on master, because the notification portlet on master did not override portal class com.liferay.notifications.hook.service.impl.JournalArticleLocalServiceImpl, thus the method
getURLViewInContext of class JournalArticleAssetRender will not be called when add a web content.

But to avoid the issue happen on master once we override class JournalArticleLocalServiceImpl in the future and also we want to keep the code sync with ee-6.2.x I sent this pull request

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29817. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by topolik** [comment]
Hi guys, can you please cc me next time on all security issues? Thanks.

**Pull request closed without merging**
