### PR TITLE
[Waiting for answer] LPS-40069 Converting fields that store Journal titles to CLOB

### PR DESCRIPTION
**Pull request by zsigmondrab**
Hi Julio,

however, these modifications touch other components also, it is basically a web content model change so I would like your team to review this first.

Thank you,
Zsigmond

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @zsigmondrab 

the changes look good to me, but don't we need to upgrade the schema? is that done automatically?

thank you!

**Comment by juliocamarero** [comment]
cc @sergiogonzalez

**Comment by juliocamarero** [comment]
Hey @hudakl 

the changes look good to me, but don't we need to upgrade the schema? is that done automatically?

thank you!

**Comment by hudakl** [comment]
Hi Julio,

I tried to test if the conversion during the upgrade is performed automatically, but I only got partial results. With Oracle the upgrade didn't finish due to a ORA-00904 error, but it got through upgrading the AssetEntry table in which the 'title' column got successfully converted to CLOB.
I'll perform further tests and I'll get back to you with the results.

Thanks,
Laci

**Comment by juliocamarero** [comment]
Hi @hudakl 

did you have time to do some testing? 

thanks a lot!

**Comment by juliocamarero** [comment]
Pull request forwarded to https://github.com/epgarcia/liferay-portal/pull/515. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
