### PR TITLE
[Technical Support] LPS-59252 & LPS-59288

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by zxdgoal** [comment]
Hey Julio

Currently, if the locale calculated from portalImpl does not match the original locale from requested layout, we go straight without redirection. That is not a big problem.

However, I18npath is a bit different. For example, if I input localhost:8080/fr/web/guest/home and French is not an available locale for site guest, I will get the site displayed in site default locale, say English, but the URL is still /fr/web/guest/home.

This is not that user-friendly and could confuses end users as locale from URL does not match the locale displayed to them.

One possible solution would be redirecting users to localhost:8080/en/web/guest/home to avoid this inconsistency.

What are your opinions?

BTW, you cannot test this pr until fixing LPS-59345 where I still struggle.

Thanks
John.

**Comment by zxdgoal** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
This part was easy: https://github.com/brianchandotcom/liferay-portal/pull/31050

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/31051. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
