### PR TITLE
LPS-59610

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @hhuijser @daviddotzhang 

even though this fixes the issue, we shouldn't make this change since other third party developers won't be able to do this.

Instead, the export-import iframe should obtain the key from the right resourceBundle. I think we already do this in other places of the portal. When do we LanguageUtil.get(ResourceBundle, key) we can pass the resource bundle of any module or even merge several resource bundles.

Could you please give that a try? Let me know if you need any help. 

thanks a lot!

**Comment by daviddotzhang** [comment]
Hey @juliocamarero @hhuijser 

I also found that this is a common issue, which exist in most of the portlets if it use export/import.

in order to implement the way you have said. I have tried the follow changes.

way 1: try to fix it in the "export_portlet.jsp" , but it does,t work because "resourceBundl"e is actually from "export/import" module.

way 2: then I try to add "resourceBundl"  in "PortletDataHandlerControl",  add change the method as follow: public String getControlLabel(),
we need to pass the locale, classloader,.
1:for classloader we need to get it from "JournalPortletDataHandler".
2:new PortletDataHandlerBoolean(classloader).

:1234: this will lead to a lot change(search "new PortletDataHandlerBoolean" , you will find it).
:1234: do you have any suggestion on this , what I said make sense ?

**Comment by juliocamarero** [comment]
Hey @matethurzo,

can you help @daviddotzhang with this? We have a small issue with the translations in the export/import module.

**Pull request closed without merging**
