### PR TITLE
[TECHNICAL-SUPPORT] LPS-60047

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ChrisKian

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/ChrisKian/liferay-portal/pull/3. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/259540f~1...259540f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32262. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/b7dab30~2...b7dab30) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32263. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/172a556~2...172a556) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
