### PR TITLE
LPS-56688 Reverting commit 6744beed547d4c1f26b15775a3d654b5e793a12b since imports are used

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by juliocamarero** [comment]
cc @leoadb  

This change broke blogs, asset publisher...

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
cc @brianchandotcom pushed to upstream since this was blocking all work on asset publisher, blogs and more apps.

**Comment by leoadb** [comment]
@juliocamarero sorry for that and thanks to let me know. Have you started portal locally after reverted that commit ? I was getting a module resolving issue on my workspace because of that.

@marcellustavares we need to remove that dependency !!!

**Comment by juliocamarero** [comment]
@leoadb what do you mean? which module?

**Comment by leoadb** [comment]
@juliocamarero dynamic-data-mapping-service and dynamic-data-mapping-taglib were not being deployed because of those imports.

**Comment by marcellustavares** [comment]
@leoadb we need to remove this dependency in any case. We cannot have the whole portal depending on DDM to boot up.

@juliocamarero, we'll take a look at this closed and see the alternatives we have.

Thanks

**Pull request closed without merging**
