### PR TITLE
LPS-58908 Uses the search iterator to paginate

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30502. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
@evannagayama this changes the markup of paginators in journal. This may break tests related to the pagination (only in portlets using lexicon, so mainly journal and site teams). Let us know if you need any ID or anything in order to fix the tests. thanks!

**Comment by evannagayama** [comment]
Thanks Julio, we'll take a look and let you know. @brianwulbern, can you also look into this and make any necessary fixes. Thanks!

**Pull request closed without merging**
