### PR TITLE
LPS-62907

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/35805

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35847. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/599c52a~4...599c52a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35859. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/3afc5e4~4...3afc5e4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
