### PR TITLE
LPS-44467 Fix lost parameters on instanceable portlets deployed on customizable regions of layouts

### PR DESCRIPTION
**Pull request by mdelapenya**
The proposed solution takes into account that once the portlet is in the customizable region, a portlet preference will be stored for that layout and portlet. Retrieving that portlet preference for the right portletId (generated by PortletInstance class) will define if the portlet is customizable, properly setting the namespace for its specific parameters (i.e. folderId in DL). cc/ @sergiogonzalez @jorgeferrer @rotty3000

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
ci:retest

**Comment by JorgeFerrer** [comment]
Good job Manu. This is a hard bug.

I've added some comments on some specific aspects of the code that I think
can still be improved

**Comment by mdelapenya** [comment]
Yeah I think I can add your suggestions :)

**Comment by mdelapenya** [comment]
Closing pull request to add Jorge's suggestions. Resent here: https://github.com/jorgeferrer/liferay-portal/pull/636

**Pull request closed without merging**
