### PR TITLE
LPS-57600

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
See Hai's explanation here: https://github.com/hhuijser/liferay-portal/pull/2440

**Comment by daledotshan** [comment]
Hey @juliocamarero 
Could you look at this pull request? it is for a EE customer

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29034. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
