### PR TITLE
LPS-58417

### PR DESCRIPTION
**Pull request by juangon**
Hi @juliocamarero. As we have been discussing, LPS-58417 will change behavior introduced in LPS-54498, so only default article locale will be validated for required fields.

This needs to be pushed first in order to do the same for backport.

Thanks very much!

### CODE REVIEW

**Comment by juangon** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30570. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
:+1:

**Pull request closed without merging**
