### PR TITLE
master-qa-24139

### PR DESCRIPTION
**Pull request by evannagayama**
https://issues.liferay.com/browse/LRQA-24139

### CODE REVIEW

**Comment by evannagayama** [comment]
@juliocamarero I kept running these in ant format-source and trying to fix the line issues, but it wouldn't work. Maybe you can show me where to separate the lines and what I'm doing wrong tomorrow.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38611. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/cbe96b9~1...cbe96b9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/evannagayama/liferay-portal/pull/696. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/cbe96b9~1...cbe96b9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
