### PR TITLE
LPS-64881 SF - attribute order

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @jbalsas

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
Failed tests are failing on all the pull and have nothing to deal with the pull's subject.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Mañana vemos esto, que no entiendo nada :)

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38851. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
