### PR TITLE
LPS-61936 Fix message presentation when shown in a popup

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @leoadb 

Could you please explain a bit more your changes? Why is this needed? why does it only affect DDL?

thanks!

**Comment by leoadb** [comment]
@juliocamarero this issue happens when a success message should be shown and the following condition evaluates to true: themeDisplay.isStatePopUp() && MultiSessionMessages.contains(renderRequest, portlet.getPortletId() + SessionMessages.KEY_SUFFIX_CLOSE_REDIRECT). 

When this scenario takes place, the success message is concatenated with the close dialog message and between them there will be a lot of new line and tab characters. These characters mess up the way the alert is built in liferay-ui:alert taglib. A missing character error is thrown by javascript trying to parse the message attribute of Liferay.Alert and the success message is not presented to the user.

Before the commit 838aa446c496855d02d03a556f579f0f4683cce7 everything works fine because a div tag is used. This commit changes the div by the use of liferay-util:buffer taglib.

I don't think this is a DDL issue. I'm tending to think this is a general issue.

Please let me know if you need something else.

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34676. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/bbdabae~1...bbdabae) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
