### PR TITLE
LPS-62689 build-lang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/6. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
