### PR TITLE
LPS-58438

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @hhuijser @zsigmondrab @yuhai 

It took me a while to understand the logic. I like @zsigmondrab' s change since that will fix the same problem in other places but I tend to think this is making the service very complex. 

Thinking of an alternative solution, could we set the same expiration date to all article versions when this property is enabled? That would seem simpler to me and it would still have @zsigmondrab's option benefits.

what do you think?
Thanks!!

**Comment by yuhai** [comment]
Hi Julio,

From my understanding, your solution is that when view and we directly set the same expiration date to all article versions. Is it right?

If so, it is ok for me. But I have two concerns and they might be not important.

1. If so, it might replace the function (checkArticlesByExpirationDate method) of CheckArticleMessageListener if someone still view the asset publisher. In addition, the first time view might take more time. But the case is rare.

2. When execute view, we will do update operation. I think it has a little deviation because we execute update operation in the process of view. If it is ok, I also can understand this. :)

Regards,
Hai

**Comment by juliocamarero** [comment]
Hi @yuhai,

no, I am suggesting something different. I am suggesting that ONLY when this property is enabled, when you UPDATE an article to certain Expiration Date, we set the same expiration date to all the versions of that article.

what do you think?

**Comment by yuhai** [comment]
Hi Julio,

Got it. From my viewpoint, it might cause one confused issue. Please see the below case:
1.I have one version article.
version:1.0, articleId:10000, expirationDate:null(never), status:0, title:title1.0

2. When we update the article(create one new version 1.1), if we set 1.1 version's for certain Expiration Date, and then we set the same expiration date to version 1.0. At this time, the two versions are the following:
version:1.0, articleId:10000, expirationDate:(14:00), status:0, title:title1.0
version:1.1, articleId:10000, expirationDate:(14:00), status:0, title:title1.1

3. Then I delete the version 1.1 immediately , version 1.0 will be displayed. But its expirationDate won't be never. (the behavior is inconsistent with previous set never).

Regards,
Hai

**Comment by juliocamarero** [comment]
Hi @yuhai 

I see what you mean, but I think even that makes sense to me as a user. Right now, categories and tags already behave that way. Setting this property to true would make the "expiration data" a common field for all versions.

let me talk to our PM to see what he thinks.

**Comment by yuhai** [comment]
Thanks, Julio.

Looking forward to your update. :)

Regards,
Hai

**Comment by juliocamarero** [comment]
Hi @yuhai 

after talking with our PM @jidtuit, we think the following would be reasonable:

- When this property is enabled, when you UPDATE an article to certain Expiration Date, we set the same expiration date to all the versions of that article. (The reason is, when users enable this property, the expiration date affects to the whole web content, not an specific version). 
- We should make this obvious to users. When this property is set to true, if a user changes the expiration date, we should display an information message explaining that this would affect the whole article, not just one version.

Let us know what you think,

thanks!

**Comment by yuhai** [comment]
Hi Julio,

I have one question regarding how to display the hint information message and when display it. 

From my viewpoint,  when this property is set to true, it means only check approved article. That is to say, we should set all the versions expiredate for same when the latest article's status for "0". 

**For those draft and pending article, we shouldn't handle them. if we handle them (set all the versions expiredate for same ) when article is draft and pending, it should go against with the property meaning.**

**So I think we may use "User Guide" to statement the explanation instead of displaying the info in UI**. Because if we display the info in UI, we can't make sure whether the article is approved(at least, when enable workflow, the status won't be approved) because we don't know the end user executes which action.

Regards,
Hai

**Comment by yuhai** [comment]
Hi Julio,

I have another question regarding the logic and it might cause import performance slowly. Please refer to the below case:

1. Import one site's web content (the web content includes 10 versions) into another site "siteA". It will invoke JournalArticleLocalServiceImpl.addArticle method->JournalArticleLocalServiceImpl.updateStatus() method, I think the fix logic should be placed in updateStatus(). This will cause when import every version and it will update the previous versions. For example, if the article includes 10 versions, for the smallest version(1.0) and it will be updated 10 times in the process of import.

2.Again import the lar into "siteA", It will invoke JournalArticleLocalServiceImpl.updateArticle method->JournalArticleLocalServiceImpl.updateStatus() method, the effect is the same as the above case.

**So should we exclude the import progress for the fix logic by using ExportImportThreadLocal.isImportInProcess()? That is to say, when import, the fix logic won't be entered. The premise case is export lar's datas have applied the fix. For previous datas, I think we may verify the datas in the process of verify. Is the logic right?**

Regards,
Hai

**Comment by juliocamarero** [comment]
That is a good point, you should do this only when you are not importing a web content. I am closing this pull request for now. thanks!

**Pull request closed without merging**
