### PR TITLE
LPS-68243

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey Julio,
Could you help to review this pull request as high priority? one ee customer is waiting for this fix

Thanks,
Dale

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @hhuijser 

this pull seems to affect search infrastructure. Could you please send this to Andre Oliveira?

Thanks a lot!!

**Comment by daviddotzhang** [comment]
Hi @juliocamarero @hhuijser 

see https://github.com/arboliveira/liferay-portal/pull/154

**Pull request closed without merging**
