### PR TITLE
LPS-55247

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/258. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hi guys, 

thanks a lot for looking into this. You have found out the root issue, but I tend to think this is not the right solution. I think the problem is that the portletDataContext.isPrivateLayout should return true when used from the public pages of a site... so I tend to think the problem is deeper :)

I have sent the pull to Eduardo since he is the leader of Site Templates and can help us better.

thanks!

**Pull request closed without merging**
