### PR TITLE
LPS-69362

### PR DESCRIPTION
**Pull request by mbowerman**
Hi @juliocamarero,

@holatuwol and I discovered that the IPGeocoderImpl had its own specific write method that made use of BufferedInputStream.read() - a method that only reads one byte when it is called. In my testing, when trying to activate the IPGeocoder portlet, I had to abort the process because it was taking too long. I waited for over an hour, and only 120 KB of the 16 MB file had been copied into the tmp directory (implying that it would have taken over 100 hours if I had allowed it to go through to completion). When I applied this fix, however, the method completed in under two seconds.

We were wondering if there was a good reason that the IPGeocoderImpl had to use this particular write method rather than using FileUtil.write. If not, please push this fix through review, because this drastically improves the performance of the activate method for the IPGeocoder portlet.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hi @holatuwol @mbowerman 

when we first created the ipgeocoder, we didn't want to add a dependency on a particular portal-kernel version with the goal that we could use this module in 6.2.x and 7.0.x. It didn't make sense to us that we had to depend on a full kernel of Liferay only to copy a file.

If we introduce this dependency, we will only be able to use the new features of the ip-geocoder in 7.0.x. I've been trying to see how much code we should have to copy here from FileUtil and it seemed a lot me since it also called StreamUtil...  we might not have other choice, but if we could avoid adding the dependency on portal-kernel, I would avoid it. What do you think?

**Comment by holatuwol** [comment]
@juliocamarero Checking the tags on Github, the API used exists in both 6.1.0-ga1 and 6.2.0-ga1

https://github.com/liferay/liferay-portal/blob/6.1.0-ga1/portal-impl/src/com/liferay/portal/util/FileImpl.java#L734-L740
https://github.com/liferay/liferay-portal/blob/6.2.0-ga1/portal-impl/src/com/liferay/portal/util/FileImpl.java#L913-L918

Am I looking in the wrong place?

**Comment by juliocamarero** [comment]
@holatuwol , you are absolutely right about that. I am talking about the dependency itself. 

Before this change, this module was liferay-independent, it could even work outside of the portal for any other project. If we add this change, now this module depends on the version 2.x of the liferay-portal-kernel (which is a huge jar file that changes very frequently).

provided group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.0.0"

Therefore, this dependency should be updated if we want it to work with kernel 3.0 or with previous Liferay versions. If we had the FileUtil and the StremUtil in a smaller jar library, then I would feel much better about it... but adding the whole portal.kernel as a dependency only to copy a file seems to me like cracking a nut with a sledgehammer  :)   what do you think?

**Comment by juliocamarero** [comment]
@holatuwol @mbowerman any thoughts about this? :)

**Comment by holatuwol** [comment]
@juliocamarero Your concern makes sense if we want to ensure that ip-geocoder can be used outside of Liferay. I'll come up with a different solution and resend.

**Comment by holatuwol** [comment]
ci:close

**Pull request closed without merging**
