### PR TITLE
LPS-60407

### PR DESCRIPTION
**Pull request by natecavanaugh**
/cc @ealonso

Hey guys,
Sorry for the delay on this one, there were some icons that I had missed the first time around.
I wasn't able to get things 100% of the way there, but I think I covered most of them.

The two things I wasn't able to do, and if you're able to help or have ideas, that'd be awesome, but it's:
1. Since we're now using the `aui:icon` taglib, there is no `useDialog` attribute, and I'm not sure if we're using it in here anymore.
2. Inside of the Add Content area, the `aui:nav-item` taglib is taking an `iconCssClass` attribute, but I don't know of any way to cascase it down. Maybe in this case we remove it, and manually add the icon?

If you guys have any questions, or there are any issues you guys see, please let me know. I'll try to send the Product Menu one along as well, but I'll need to double check and make sure I didn't miss too much.

Thanks guys,

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @natecavanaugh 

the new icons looks really nice! Great job on that!!

Regarding this pull, I see some issues that I wonder if you had any idea how to solve:

1) The eye for the togggle edit controls stops working (I think it is related to some of the classes you have removed that are used from the js component)

2) Some of these icons become unaccessible for blind users if they don't have a label or a title. The liferay-ui:icon would use the message as title when the text was not shown. We need to do something similar here. Maybe adding a title attribute to the icon taglib would be enough.

3) Adding this to the taglibs could help so that they can receive any other html attribute even if it is not defined in the taglib: InlineUtil.buildDynamicAttributes(dynamicAttributes)

Regarding your questions:

1) We are not using anymore the useDialog for the control menu. We just kept it so that other users could use but we can get rid of it for now. We would need to remove it from the API though.

2) I can't find the icon you are mentioning. Can you please give me more details to see what we can do?

Thanks a lot!

**Comment by juliocamarero** [comment]
Pull request forwarded to https://github.com/jorgeFerrer/liferay-portal/pull/603. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by natecavanaugh** [comment]
Heya Julio,
I'll try to respond to each of the questions:
> Hey @natecavanaugh

> the new icons looks really nice! Great job on that!!

> Regarding this pull, I see some issues that I wonder if you had any idea how to solve:

> 1) The eye for the togggle edit controls stops working (I think it is related to some of the classes you have removed that are used from the js component)

Yeah, I noticed that, though I think the functionality was still working, but just the icon wasn't switching. I also have to figure out how to handle that, since it's not just a CSS class change, but rather swapping out the elements themselves.

> 2) Some of these icons become unaccessible for blind users if they don't have a label or a title. The liferay-ui:icon would use the message as title when the text was not shown. We need to do something similar here. Maybe adding a title attribute to the icon taglib would be enough.

Yeah, I think I may just have screwed up. I put the image as the title, but it should instead be the label. I can take a look at doing that.

> 3) The previous icons used to have a tooltip also. (An icon alone may not be enough information and having some textual help is very useful)

Yeah, this part, I'm not sure 100% what to do (whether to modify the taglib API to match more closely the liferay-ui:icon taglib, or some other approach).

> 4) Adding this to the taglibs could help so that they can receive any other html attribute even if it is not defined in the taglib: InlineUtil.buildDynamicAttributes(dynamicAttributes)

Ah that's a good point, I can add that in.

> Regarding your questions:

> 1) We are not using anymore the useDialog for the control menu. We just kept it so that other users could use but we can get rid of it for now. We would need to remove it from the API though.

That makes sense. Since it's not doing anything right now, I'll leave it for now until we're ready to commit it in.

> 2) I can't find the icon you are mentioning. Can you please give me more details to see what we can do?

Sorry Julio, I meant [this guy](https://github.com/natecavanaugh/liferay-portal/blob/d3fb833be3718439099b38f8d1c0bc36d17bc6e6/modules/apps/control-menu/control-menu-web/src/main/resources/META-INF/resources/add_content.jsp#L57), not the `aui:nav-item` taglib.

Thanks a lot for the responses :)

**Comment by juliocamarero** [comment]
Thanks a lot for your answers Nate,

regarding the last one: 

2. Inside of the Add Content area, the aui:nav-item taglib is taking an iconCssClass attribute, but I don't know of any way to cascase it down. Maybe in this case we remove it, and manually add the icon?

@ealonso is planning to get rid of the app-view-display-style taglib and use some custom code, so we could definetively use custom icons there.

Since I think you want to make some changes, I am closing the pull for now but feel free to send me another or reopen this one if you still want me to have a look.

thanks a lot!!

**Pull request closed without merging**
