### PR TITLE
LPS-70119 SEMVER

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc @SGM3, @marcellustavares, @inacionery

Hey guys.

I've modified the logic of the Document Selector url generation in DDM, since it wasn't working as expected.

I've check it and it seems that, since the url is a "control panel", the p_p_auth should pass the right plid (the site admin plid) and to do this we should create a virtual layout.

I've rollbacked some of your changes, and fix the logic.

**Comment by inacionery** [comment]
@leoadb

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
Hey @juliocamarero 

SF doesn't fail in my system

Do you have more info about the error??

Thanks!

**Comment by marcellustavares** [comment]
thanks @robertoDiaz!

**Comment by jcampoy** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
@juliocamarero 

Closing to fix SF

**Pull request closed without merging**
