### PR TITLE
Use response instead so that we can do a PipingResponse (othewise, the view is rendered in randon places of the page)

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
waiting for plugins commit

**Comment by jkappler** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28017. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/c3adb50~2...c3adb50) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
