### PR TITLE
LPS-61533 SF - js

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by dantewang** [comment]
cc @alanzh

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/3880. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/dad87bb~7...dad87bb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/evannagayama/liferay-portal/pull/390. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/028db41~4...028db41) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
