### PR TITLE
LPS-55246

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @Preston-Crary

Hey Julio,

I wasn't sure who this should go to since it touches pretty much everything. Let me know if you'd like someone else to take a look though.

Thanks!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/Preston-Crary/liferay-portal/pull/24. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/765f39d~1...765f39d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/3376. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/765f39d~1...765f39d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @Preston-Crary 

 I have fixed one broken test about the PM, but this change is somehow breaking all the tests for the MBAttachmentTests. could you please have a look? https://github.com/Preston-Crary/liferay-portal/pull/24
 
thanks!

**Pull request closed without merging**
