### PR TITLE
[TECHNICAL-SUPPORT] LPS-54251 In Oracle DB, SEO description, keywords and robots fields with more than 4000 chars can't be saved

### PR DESCRIPTION
**Pull request by moltam89**
Hey Julio,

I used [LPS-44439](https://issues.liferay.com/browse/LPS-44439) as the pattern.

Tamás

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @moltam89 

this change doesn't make sense to me.... (despite we already applied it in the other ticket).

We do have many other localizable fields which are not CLOBS, for example the "title" just above should have the same problem. why isn't this failing?

If this is the way to go, I tend to think we should apply this into Service Builder directly instead of applying it field by field.

Let me know what you think, 
thanks!

**Comment by moltam89** [comment]
Hey Julio,

I don't think this change is necessary for title fields, as titles should be much shorter than e.g. the descriptions.

However, I agree that there are other fields which are affected, I was concentrating on the customer's current issue.

Should I create a general LPS, to solve these kind of problems?

Thanks,
Tamás

**Comment by juliocamarero** [comment]
Yes, I tend to think this is a Core Infrastructure issue that should be solved at the Service Builder level. 

Thanks a lot!

**Pull request closed without merging**
