### PR TITLE
LPS-54570 Added check if scopeGroupId passed to addCategory method via ServiceContext is proper

### PR DESCRIPTION
**Pull request by kgolebiowski**
Hello Julio,
I'm sending you a pull request with fixing the bug I spotted recently. I don't know if we can call it a bug or rather an API inconsistency, but it is definately confusing. I don't know if you have any strict rules concerning *groupId* validation. As far as I know in most cases it is passed as an parameter explicitly (which then is hard to miss), but in  in case of *AssetCategories* it is passed using *serviceContext* and there is no javadoc about what is required. That's why I think it should be validated in some way (or maybe a new explicit parameter should be introduced to *addCategory* method?).

My workaround should throw *NoSuchGroupException* if the Group does not exist.

Regards,
KG

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/386. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @kgolebiowski 

I totally understand the problem you are describing. I fully agree that it is very confusing that the groupId is not in the signature of the method but it is required.

I look at how we validate this in other situations and I found that we don't usually validate the groupId in the way you did. If I tried to merge your contribution then we would need to apply that same pattern to every service accepting a groupId.

Since that would mean a lot of work, I think that at a first step we can improve the API making the groupId visible in the method signature so I went ahead and added it to all the services following this pattern.

Let me know what you think.

If you think the validation of the groupId is still interesting, you can try to contribute that, but the change should be applied to all services in portal, not only to the Categories Service.

Thanks a lot for the contribution!!! We really hope you keep contributing to Liferay Portal! :+1:

**Comment by kgolebiowski** [comment]
Hi @juliocamarero 
Your solution is perfectly fine for me. I also found out groupId is not verified in other services and it is (instead of that) always present in method signature. I know that rebuilding core services (and verifying all the dependencies) is really difficult and I didn't know your internal policy about that process so I just submitted a workaround that could save other's people time. If you managed to change the API that's great, I have no further questions :) Thank you for quick response.

**Comment by kgolebiowski** [comment]
But' I have one question :) Should I withdraw that commit from my repository somehow? I'm afraid that github will try to send it together with my future pull requests.

**Comment by juliocamarero** [comment]
Yes, I would recommend you to keep your "master" branch in sync with the master branch from Liferay and then have other branches for your work. That way, you can always send pull requests based on the latests clean code.


thanks!

**Comment by kgolebiowski** [comment]
Thanks for you hint, I've cleaned up my master branch and will create separate tempotary branches for future fixes.

**Comment by juliocamarero** [comment]
:+1:

**Pull request closed without merging**
