### PR TITLE
LPS-53643 [Waiting for answer]

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Julio,

I'm sending this through you since it is dealing mostly with the Asset Publisher behavior but it might be good to have @matethurzo take a look at it since the bug was found while staging.

Thanks!

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@ChrisKian Please make sure these tests aren't breaking because of your fix.

**Comment by ChrisKian** [comment]
These failures seem to have to do with message board notification; my fix is only related to properly scoping structures within an asset publisher.  They are completely unrelated.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @jonathanmccann @ChrisKian 

I tend to think your changes will break the feature to support filtering by structures in the hierarchy of sites since you are now using only the current site. can you confirm this is not the case?

why is the structure from B being stored in asset publisher in A?

thanks!

**Comment by matethurzo** [comment]
Hey,

This seems to be one of them famous group id issues. As long as Julio is ok with this and the group ids are the proper ones, I'm perfectly fine with this.

Thanks!

**Comment by ChrisKian** [comment]
Hi @juliocamarero,

  You are right that the hierarchy is affected when attempting to filter by structure type.  Here are my findings:
1) Before my changes, all structure types could be filtered on, regardless of whether or not they were in scope or in the hierarchy.  Site A could filter on Site B structures, even when not in scope.
2) With my current change, only the assets in scope can be filtered on.  These scopes must be explicitly added by the user; hierarchy is ignored unless it is added to this scope.
3) I can easily include groupIds of parent sites, thus ensuring we can filter on all assets within scope AND hierarchy.  However by doing so they become missing references during the import/export process.

I believe the outcome from #3 should be acceptable; we are attempting to export a child site without the parent site, so there will naturally be missing references.  Also, when we add Site B to Site A's scope and attempt to export, we generate missing references on Site B Structures.  This is identical to what will happen with #3.

Please let me know if this is acceptable; I will be updating the pull request shortly.

Thanks!

**Comment by juliocamarero** [comment]
Hi @ChrisKian 

I think it is ok if those become messing references during the import/export process as long as the message shown to the user explains what is going on.

thanks!

**Pull request closed without merging**
