### PR TITLE
LPS-55247

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hi @BryanEngler @jonathanmccann 

I tend to think this code is already somewhere else because if you tests the same thing with staging, the preference and the scope is propagated to life.

Could you please have a look at it to see if we can avoid adding this code? @matethurzo can help you find where we are doing this for staging.

thanks!

**Comment by BryanEngler** [comment]
sent a new pr to mccann https://github.com/jonathanmccann/liferay-portal/pull/680

**Pull request closed without merging**
