### PR TITLE
LPS-56702 Apply new settings framework in Web Content Service and Web Content Administration OSGI Modules (waiting for the postprocess)

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
We still need to postprocess the settings (if possible)

**Comment by jkappler** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28013. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28053. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
