### PR TITLE
LPS-52763 [Waiting for answer]

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @BryanEngler @jonathanmccann 

I am very confused by this change. Why does this code solve the issue?

What would happen if the article is expired for some time and enabled again later?

**Comment by BryanEngler** [comment]
hey julio,

so if you look in com.liferay.portlet.assetpublisher.action.ConfigurationActionImpl, we have the moveSelectionUp/Down methods...

these methods get the assets to rearrange from the "assetEntryXml" portlet pref. expired assets are still present in this pref, even though they are not visible. so the number of visible assets are not in sync with the number of assets in the "assetEntryXml" pref. when we go to rearrange the assets, this inconsistency in the counts causes the behavior seen in the lps.

so the goal of this fix was to have the assets stored in the "assetEntryXml" pref match the assets that can be seen in the AP configuration under 'Asset Entries' for manual selection.

if the article was published again later on, the user would have to manually add it back to the entries in the AP config so that it would display again. this was something that i talked to a few other people about because i wasnt sure if that would be the expected behavior for most users, but the people i talked to pretty much agreed that this would be better than articles automatically reappearing after publishing an article that had previously been expired... so even though the user had manually added it in the past, expiring the article removes it, and since its configured as "manual selection", i felt like it would be best to manually select the article again... but if you disagree then just let me know and we can look into a different solution.

hope that helps! let me know if you have any other questions

**Comment by juliocamarero** [comment]
Ok, I understood your changes now.

mmm... I am torn with the solution....

This change will affect many other places, not only "expiration". For example, moving to the recycle bin and restoring will have the same effect.

Usually, we try to make the "Undo" when you move something to the recycle bin fully reversible. Right now, if you have a web content shown in asset publisher (manually selected) and then you move it to the Recicle bin (by mistake) and you undo, you will have lost the configuration in the asset publisher. Or the same will happen if there is workflow enabled and there is a minor edit in the web content.

I would prefer not to remove the results if that is possible...  what do you think?

**Comment by BryanEngler** [comment]
ok ya i see the issue there...

maybe we can somehow still show expired articles in the AP config but have them grayed out etc...? this way you would be able to reorder the articles properly, and it would also give you the option to remove the expired article from the selection, because at this point the expired article just disappears and you cant remove it from the selection if you wanted to. this would require a bit more work but might be the best solution?

**Comment by juliocamarero** [comment]
That solutions sounds really awesome to me, you are right. If you can do that, that would be my favorite :)

I am closing this one then.

Thanks a lot Bryan!

**Comment by BryanEngler** [comment]
sounds good. ill take a look and let you know if i have any questions

**Pull request closed without merging**
