### PR TITLE
LPS-62194 Change an element not present

### PR DESCRIPTION
**Pull request by asungutierrez**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Pull request forwarded to https://github.com/juliocamarero/liferay-portal/pull/3929. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by asungutierrez** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/evannagayama/liferay-portal/pull/414. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34799. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
