### PR TITLE
LPS-59252

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey @juliocamarero ,
Could you take a look about this fix? it is for a ee customer.
Thanks

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @zxdgoal, 

would it be possible for you to add an integration test for this?

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/zsigmondrab/liferay-portal/pull/118. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zxdgoal** [comment]
Hey Julio

I added one, see https://github.com/hhuijser/liferay-portal/pull/2519.

**Pull request closed without merging**
