### PR TITLE
LPS-62328 validate document library links only for current portal URL

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/matethurzo/liferay-portal/pull/1427. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
