### PR TITLE
[WAITING FOR ANSER] LPS-67287

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @hhuijser @yuhai @daledotshan 

I have one question, even though this fix will avoid the exception to be thrown.. is this the root cause? why are we trying to delete a file that doesn't exist anymore?

thank you!

**Comment by yuhai** [comment]
Hi Julio,

Please refer to the below explanation:

When move mbthread with attachment to Recycle Bin, we will add related dlfileentry data in trashentry. At this time, it has two datas in trashentry.
1. MBThread
2. DLFileEntry

When delete datas from trashentry, firstly delete MBThread(1) and it will delete its attachment (dlfileentry data: including related trashentry table). The main problem is that the DLFileEntry(2) still exists (this is from actionableDynamicQuery.performActions() before deleting logic), and the trash check tries to clean it, but because the deletion of MBThread entry deleted the DLFileEntry row already, the corresponding DLFileEntry data has not existed., thereby throwing the "No FileEntry exists with key..."

This fix uses this way to skip the delete logic. As far as I know, the case only adapt with model(wiki,KB,MBThread) with attachment.

Regards,
Hai

**Comment by juliocamarero** [comment]
Hey @yuhai 

I am not sure I understood everything you said.

I don't like the fact that we catch every Exception just for this situation since we would be hiding other possible errors in the future.

Would it be possible to delete the trashEntry of the DLFileEntry when deleting the MBThread? That way, the actionableDynamicQuery wouldn't find it, right?

**Comment by yuhai** [comment]
Hi Julio,

>Would it be possible to delete the trashEntry of the DLFileEntry when deleting the MBThread? 
Yes, because when delete one MBThread from Recycle Bin, we needs to delete attachment data(this will execute delete DLFileEntry logic.) 

I want to explain the root issue again.
1. When move mbthread with attachment to Recycle Bin, we will add related dlfileentry data in trashentry. At this time, it has two datas in trashentry.
trashEntry1: MBThread
trashEntry2: DLFileEntry

2. When com.liferay.trash.web.internal.messaging.CheckEntryMessageListener execute, it use "select * from trashentry" to fetch these two datas. And then we use loop to delete them (refer to https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/trash/service/impl/TrashEntryLocalServiceImpl.java#L145--#L171)
For trashEntry1: when delete trashEntry1 MBThread, its will invoke delete DLFileEntry logic so that entryId:2 DLFileEntry can be deleted from trashentry.

For trashEntry2: when the loop delete trashEntry2: DLFileEntry, this data DLFileEntry has been deleted when delete trashEntry1: MBThread. So the issue occured.

**Summary:**
So the issue is when we fetch the list(actionableDynamicQuery.performActions();) to delete datas from trashentry, we can't find MBThread and DLFileEntry relation from the sql. So that we can't filter MBThread's attachment data from the list. They will be deleted one by one. When delete MBThread, related DLFileEntry(attachment) can be deleted. However, DLFileEntry still existed in list, and when delete DLFileEntry, the issue occured.

So for the below question.
>That way, the actionableDynamicQuery wouldn't find it, right?
My answer is no, it can find the trashEntry2: DLFileEntry, so the issue occured.

If I misunderstand your questions, please let me know. :)

Regards,
Hai

**Comment by juliocamarero** [comment]
Thanks your for explanation @yuhai!

I have understood the problem now. Then, the root issue here is that the attachment shouldn't create a TrashEntry when the thread is moved to the recycle bin. Only things that are explicitly moved to the Recicle Bin create a trashEntry.

Can you please coordinate with @sergiogonzalez for this change? Looking at the code, we call at this method from MBThreadLocalServiceImpl: PortletFileRepositoryUtil.movePortletFileEntryToTrash, but it seems that method is doing more that it should for our case.

Thank you!

**Comment by yuhai** [comment]
Hi Julio,

I am not sure whether the behavior "the attachment shouldn't create a TrashEntry" is right. I checked DLAppHelperLocalServiceImpl.restoreFileEntryFromTrash(), it used trashEntry to restore dlFileEntry data.

We will coordinate with @sergiogonzalez to confirm this change.

Regards,
Hai

**Comment by yuhai** [comment]
Hi Julio,

Sorry. I just understand your meaning. You have confirmed the behavior "the attachment shouldn't create a TrashEntry" is right. I will try to fix the issue by using your guide way.

Regards,
Hai

**Pull request closed without merging**
