### PR TITLE
[Technical Support] LPS-65193

### PR DESCRIPTION
**Pull request by dustinryerson**
@BryanEngler

https://issues.liferay.com/browse/LPS-65193

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @matethurzo, can you please confirm this makes sense to you? thanks!

**Comment by juliocamarero** [comment]
@epgarcia can you please confirm this makes sense to you? thank you!

**Comment by matethurzo** [comment]
@juliocamarero @BryanEngler I don't fully understand the change. It seems ok, but I'd like to know more about it, what is the problem. So far for me it seems we trying to avoid and overwrite but this can cause problems if not all the attributes are being propagated during an import.

**Comment by matethurzo** [comment]
@juliocamarero @BryanEngler I don't fully understand the change. It seems ok, but I'd like to know more about it, what is the problem. So far for me it seems we trying to avoid and overwrite but this can cause problems if not all the attributes are being propagated during an import.

**Comment by juliocamarero** [comment]
Hey @BryanEngler @dustinryerson 

could you please answer to Mate's concern?  thanks!

**Comment by BryanEngler** [comment]
ya the problem is that the source template of the site is being overwritten when the lar is imported because the site in the lar was based off of a different template. so this fix just prevents that from happening. 

this fix was kind of a suggestion from Tamas Molnar on LPP-20751. the ticket was then assigned to me so i emailed zsigmond to see if he thought that the idea would work, and he said that it would be acceptable to send a pr even though he didnt get to look into it too closely. so i didnt spend a whole lot of time looking into the issue myself, but i didnt see any other issues when i was testing the fix so i sent the pr to see if you guys would find anything that might be wrong.

**Comment by epgarcia** [comment]
Hi @BryanEngler and @matethurzo,

In other words: the change prevents an imported site to be linked to the same site template as the exported site, right? Then I have two questions: (1) Do we want this information to be imported (i.e. we have a valid use case for this)? Or (2) was this code aimed for the site-template-to-site propagation only?

About (1), I'm not sure it makes sense to import this information. We don't have this use case for staging, since site-template based sites are not stageable. As for export/import, can a exported site have a site template as dependency? On the other hand, if the scenario is (2), I'd move the `setLayoutPrototypeUuid` code inside the `else if (larType.equals("layout-set-prototype"))` block to make clear that this is the only observed case.

**Comment by matethurzo** [comment]
@epgarcia @BryanEngler 

I've had a conversation with Tamás and Zsigmond about this issue, and here is what we have concluded:
- We have two site templates: T1, T2
- We have two sites created based on the templates, S1 and S2 respectively.
- We are exporting S1 and importing it to S2.

The issue is that the template link in S2 is overwritten to T1 by the import process.

Regarding staging Eduardo is right. Although export/Import should export and import this information actually there is a validation built around this to validate if the template is present on the target environment as well.

Image if we have a third site without any template called S3. We are importing the LAR into there and the T1 is changing we want to change the structure in S3 as well.

In this case what we would really need to decide how should we work in the case of S1 being imported to S2. Based on the conversation with the support it seems to be that the customer was trying to move data only, but they didn't want to export all the portlets one by one so they exported the whole site and this resulted in this situation.

What do you think?

**Comment by epgarcia** [comment]
I see three options:

1) Import the reference to the original site template, if the target site doesn't have one already. 
2) Never import the reference to the original site template
3) Add an option in the export/import UI like "export/import reference to site template"

Personally, I prefer 2).

**Comment by juliocamarero** [comment]
@BryanEngler  what do you think about Eduardo and Mate's comments? do you know what to do?

**Comment by matethurzo** [comment]
@epgarcia @BryanEngler I think the best would be if the user could choose basically option 3.

Basically I think going with option 2) is feature loss, and we might see some users complaining about it. We had some behavior changed in the past and later we found out that these are actually used by someone. Before we remove that option I think we should involve PM to ask the customers, etc. So I'd let the user choose for now then later we can remove it if it's safe.

**Comment by juliocamarero** [comment]
@dustinryerson  I am going to close the pull since it's been open for more than a month now. Can you please coordinate with @epgarcia and @matethurzo in order to send a new one?

thanks!

**Comment by dustinryerson** [comment]
Sounds good, thanks @juliocamarero!

**Pull request closed without merging**
