### PR TITLE
LPS-68301

### PR DESCRIPTION
**Pull request by eperezg**

### CODE REVIEW

**Comment by eperezg** [comment]
ci:reopen

**Comment by eperezg** [comment]
ci:retest

**Comment by epgarcia** [comment]
ci:retest

**Comment by eperezg** [comment]
Hi @epgarcia,

This issues is only fixed on 6.2.x, this is the pull for the master branch.

Regards,
Eduardo.

**Comment by epgarcia** [comment]
ci:retest

**Comment by epgarcia** [comment]
Hey @eperezg ,

Thanks for the response. We're getting two test errors with your changes. I run tests several times to make sure they're actually related to those changes. Could you please check it?

Thanks

**Pull request closed without merging**
