### PR TITLE
LPS-61592 set errorSection attribute to null to expand correct panel or tab with validation error

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by jbalsas** [comment]
Increíble, @pavel-savinov, muchísimas gracias!

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/34897. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
