### PR TITLE
LPS-47199 User is unable to view owned draft web content in home tab in control panel

### PR DESCRIPTION
**Pull request by zsolah**
Hello,

Please review.
This change in LPS-60216 has caused LPS-47199 to not work at master.

Thanks,
Zsolt

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
@ealonso can you confirm this make sense to you? thanks!

**Comment by jkappler** [comment]
@juliocamarero, draft is not visible because of the status filter, changing it will display it. (Can be seen in the picture of the ticket)

**Comment by juliocamarero** [comment]
Hey @zsolah 

I am closing this pull as per @jkappler 's comment. Feel free to reach him to discuss this. 

thanks!

**Pull request closed without merging**
