### PR TITLE
LPS-56313

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

Hey Julio,

I'm not sure if it's better to pay the performance price when searching or removing the category from the portlet preferences when the category is deleted. Let me know what you think.

Thanks!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
good point @jonathanmccann.... I would also delete the preference if you have the chance to do it.

thanks!

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27815. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
