### PR TITLE
LPS-67509 Don't let the portlet crash if there is a DB error thrown

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
@jorgeFerrer what do you think of this change? maybe we should apply this everywhere?

**Comment by JorgeFerrer** [comment]
Hey @juliocamarero,

If I remember correctly the method is meant to return false only for exceptions that the portlet doesn't know how to handle and would break even more dramatically if it's not handled by the platform. 

Seeing this change, in which only one exception (and a very generic one) is added, makes me think (and I've just confirmed it with Jurgen) that this portlet is already able to handle *any* exception. If so, should this method just "return true" to avoid the ugly "This portlet is temporarily unavailable" messages in all circumstances?

Jorge

**Comment by juliocamarero** [comment]
Hey @JorgeFerrer 

after having a look at the code, I've just verified that any portlet is able to handle any exception, the code is not specific to the layouts admin, it's in render_portlet.jsp and portlet_messages.jspf, therefore we could get rid of the isSessionErrorException method in the MVCPortlet and have the LiferayPortlet.java always add the Exception to the session.

These are the specific code lines related to this:

- LiferayPortlet.java;processAction --> we only catch those exceptions from the isSessionErrorException method. (I think we should always do this)
- render_portlet.jsp --> variable portletException; If there is any exception not captured while rendering our portlet, this variable will be true and therefore it will render the portlet_error.jsp (X is temporarily unavailable).
- portlet_content_wrapper.jspf --> <liferay-theme:portlet-messages -->page.jsp
There is a generic <liferay-ui:error /> at the bottom that will render the error message for any portlet that has an exception added to the SessionErrors.

**Comment by juliocamarero** [comment]
Hey @JorgeFerrer 

it seems all portlets are able to handle any exception, not only the Layouts Admin Portlet.

These are the key parts of the code related to this:

* LiferayPortlet.java;processAction --> Only the exceptions checked by the isSessionErrorException are introduced as a SessionError, the rest are thrown and captured later by the render_portlet.jsp (see variable portletException that captures any exception and renders the portlet_error.jsp, which prints the message X is temporarily unavailable)
* portlet_content_wrapper.jspf --> <liferay-theme:portlet-messages --> page.jsp contains in the bottom this taglib that will print a generic error message for any exception added to SessionErrors	<liferay-ui:error />

Therefore, it seems we could have every to always print their error messages using this mechanism instead of showing the generic error. Can you think of an scenario in which we would prefer to print the generic error screen?
The new solution has the benefit that all values sent in the form are kept.

**Comment by juliocamarero** [comment]
https://github.com/jorgeFerrer/liferay-portal/pull/807

**Pull request closed without merging**
