### PR TITLE
[TECHNICAL-SUPPORT | Jan 19] LPS-52435

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-52435

Please, find all related information on the ticket description.

Regards,
-tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
Rebased to latest master.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/23183. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/lipusz/liferay-portal/pull/55. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
