### PR TITLE
[Technical Support] LPS-65342

### PR DESCRIPTION
**Pull request by dustinryerson**
@BryanEngler @ChrisKian 

https://issues.liferay.com/browse/LPS-65342

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hi @dustinryerson 

thanks a lot for sending this change. However, this fix goes against the modularity of the product. The Group Service shouldn't be aware of anyone creating content scoped to that site.

It should be the "Content" services the ones who do something when a group is deleted. When you delete a site, it actually iterates all services that can contain data and call them. You can include annoucements there implementing the method deleteData in the portletDataHandler. You can see how other services such as blogs do this.

See also the call to deletePortletData in GroupLocalServiceImpl.

Thanks a lot!

**Comment by dustinryerson** [comment]
Thank you for the information you provided @juliocamarero. It's very helpful to increase our understanding of maintaining the modularity of the product. I've talked with Chris and he is already working on a new solution based on the details you mentioned. We appreciate your input on this!

**Comment by ChrisKian** [comment]
Hi @juliocamarero,

Would the deleteData method within the portletDataHandler class also apply if there is no announcements portlet within the group?  It's possible to create announcements scoped for one group from an entirely different group.

Thanks!

**Comment by juliocamarero** [comment]
Hi @ChrisKian 

when you  delete a group, you get a call to your dataHandler. From there, you can do all the custom logic you need to clean the announcement as needed. Let me know if you need some help. 

thank you!!

**Comment by ChrisKian** [comment]
Thanks @juliocamarero!

**Comment by ChrisKian** [comment]
See the new PR here: https://github.com/BryanEngler/liferay-portal/pull/163

**Pull request closed without merging**
