### PR TITLE
LPS-55306

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26150. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/593bc74~1...593bc74) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @jonathanmccann @BryanEngler 

the logic for journal was wrong. I just pushed the fix to upstream.

**Comment by BryanEngler** [comment]
ya i noticed the SF was wrong... "!" shouldnt be in front of "search"... also there seemed to be an issue with the details disappearing from the content when the actions box was checked...

**Comment by juliocamarero** [comment]
mm... what's the second issue? I am not sure I have fixed that one....

**Comment by BryanEngler** [comment]
i linked a screenshot on LPS-55306. the font changes color on the content so that you cant really see it any more. im not sure if your changes caused it but i dont rememeber seeing that happen in my original testing

**Comment by juliocamarero** [comment]
Weird.... we didn't change any css.... is that still happening? were you able to figure out what is going on?
thanks!

**Comment by BryanEngler** [comment]
hey julio, the behavior i saw with the text/highlighting was actually occurring before this LPS, so its nothing that we caused and i think we should be good. thanks again!

**Comment by juliocamarero** [comment]
:+1:

**Pull request closed without merging**
