### PR TITLE
LPS-59896 SF

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
@juliocamarero I have only taken a very quick look. I haven't tested it or reviewed the SQL in depth.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
@JorgeFerrer this change is related to the Users API. The sites portlet is calling the right API, but the implementation has some issues. I am not an expert on this API and I am not sure of the consequences of this change, but I would prefer someone else to review this pull. Looking at the code it seems Shuyang and Preston-Cary have been some of the most active developers of this API in the last years. I am going to send it back to you for now. Thanks!

**Comment by juliocamarero** [comment]
Pull request forwarded to https://github.com/JorgeFerrer/liferay-portal/pull/604. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Ok, sorry about that, I just looked at the description and not at the code changes.

**Pull request closed without merging**
