### PR TITLE
[TECHNICAL-SUPPORT] LPS-62943

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman

### CODE REVIEW

**Comment by AngeloJ** [comment]
ci:retest

**Comment by AngeloJ** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36348. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
