### PR TITLE
LPS-58669

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zxdgoal** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/416. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
