### PR TITLE
LPS-61533 Lazy loading product menu -- CONTENT ON DEMAND

### PR DESCRIPTION
**Pull request by dantewang**
**CONTENT ON DEMAND**

Alan helped to make the change with two ways. This is the first one, which **always keeps the product-menu portlet on the page but makes the portlet itself to load actual content on demand**. With this way, we still have the portlet processing overhead when loading the page even if the panel is closed. It may provide benefit in other area though.

The second one is here:
https://github.com/juliocamarero/liferay-portal/pull/3873

### CODE REVIEW

**Comment by slnn** [comment]
Here is the test results on Log In

Portal Version |Session Count | Log In Mean Time
------------ | ------------- | ------------- 
BaseLine | 6996| 181
https://github.com/juliocamarero/liferay-portal/pull/3872| 10887| 162
https://github.com/juliocamarero/liferay-portal/pull/3873 | 11366| 171

**Comment by slnn** [comment]
Here is the test results on Log In

Portal Version |Session Count | Log In Mean Time
------------ | ------------- | ------------- 
BaseLine | 6996| 181
https://github.com/juliocamarero/liferay-portal/pull/3872| 10887| 162
https://github.com/juliocamarero/liferay-portal/pull/3873 | 11366| 171

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/juliocamarero/liferay-portal/pull/3874. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/8c92bce~5...8c92bce) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
