### PR TITLE
LPS-52494

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Julio,

I'm sending this to you since it is dealing more with the front end, but let me know if it should go to someone else.

Thanks.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hi @jonathanmccann 

I am sending this to Sergio since the whole conversation started with Document Library.

thanks!

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/1891. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
