### PR TITLE
LPS-53737

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @arbetts

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Hey Julio,

For this pull, we decided it would be best to remove everything dealing with tag permissions since:

1. It was deprecated in 6.2 (LPS-39763) and should be removed in 7.0
2. We do not want users to think that this functionality exists when it actually doesn't do anything

Please let me know if you  have any questions or concerns. Thanks!

**Comment by arbetts** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
I think we need to add at least the permission to delete tags. Otherwise, any user can delete tags that other users have created.

thanks!

**Comment by arbetts** [comment]
I believe that only users who can view the tags admin portlet through the control panel would be able to delete them. I didn't think this would pose a security risk since we cannot really set the permissions for tags in a granular way.

I will test this

is it a problem if users who can view the tags admin portlet can delete tags?

**Comment by juliocamarero** [comment]
Hey @arbetts 

we also have web services, and you are exposing the remote service through the API without a security layer, therefore, anyone with the url could delete tags.

I think that adding a permission at the same level of ADD_TAG called DELETE_TAGS could solve the issue.

**Comment by arbetts** [comment]
Thanks @juliocamarero !

I will work on adding the DELETE_TAGS so we can manage those remote services.

**Pull request closed without merging**
