### PR TITLE
LPS-65809 Deprecate AssetTagStats

### PR DESCRIPTION
**Pull request by Preston-Crary**
Only things I am not sure about is the changes to DataFactory and if we should remove AssetTagStats from the asset/service.xml's [here](https://github.com/juliocamarero/liferay-portal/commit/cd675fb0686139eeaa22a4204f067ec32bedf868#diff-ea9e7fa5c654e562b1b8f2cac2b151a1L351).  Running gw baseline in modules/util did not complain about removing the public method from DataFactory.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Force pushed up the change to packageinfo.

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39879. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
👍 @Preston-Crary

**Pull request closed without merging**
