### PR TITLE
[TECH SUPPORT] LPS-71578 LayoutRemoteStagingBackgroundTaskExecutor is vulnerable of the unnecessarily to java.io.InvalidClassException

### PR DESCRIPTION
**Pull request by rimisaadouwork**
Hi,

Could you please review this commit:
https://issues.liferay.com/browse/LPS-71578

Thanks!

### CODE REVIEW

**Comment by matethurzo** [comment]
hey @rimisaadouwork please send this to me, this is staging related. i guess @juliocamarero won't mind ;)

**Comment by martaeli** [comment]
@rimisaadouwork I was wondering if you had already sent this pull to matethurzo and if this pull could be closed.

**Comment by rimisaadouwork** [comment]
Hi @martaeli,

I did sent this the PR to Mate. According to the LPS the PR is assigned to Brian. See https://issues.liferay.com/browse/LPS-71578.

Thanks!

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
