### PR TITLE
LPS-63559 hide the default portlet back icon.

### PR DESCRIPTION
**Pull request by neilking**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/36960. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/ecd55aa~2...ecd55aa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by neilking** [comment]
So we need to keep the new icon. Originally the header shows a title "Search", the new icon doesn't show a title because the portlet's decoration id is "bearbone". Is it okey?

**Comment by juliocamarero** [comment]
yes, that's the new pattern in lexicon. Feel free to reach the UX team if you think this can be confusing.

Thank you!

**Pull request closed without merging**
