### PR TITLE
LPS-64908

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @juliocamarero,

Attached is an update for http://issues.liferay.com/browse/LPS-64908.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey Jon, 

I think the root cause was the custom ajax code. 

I tried to fix it in a different way here: https://github.com/brianchandotcom/liferay-portal/pull/39211

let me know what you think.

thank you!

**Comment by jonmak08** [comment]
Hey @juliocamarero,

Your fix looks good.  Thanks for reviewing!

**Pull request closed without merging**
