### PR TITLE
LPS-63373 set image max width in journal content display to prevent overflow

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Closing until we review if this affects to asset publisher also. thanks!

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2939. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by duracell80** [comment]
max-width : 100% may not work in IE if Flexbox is being used, same as with height : auto may not work under IE11 if Flexbox is being used.

**Pull request closed without merging**
