### PR TITLE
LPS-58100

### PR DESCRIPTION
**Pull request by jcampoy**

### CODE REVIEW

**Comment by jcampoy** [comment]
Hi Julio, 

BTW: I found some issues with the Page Admin while I was implementing this feature.

https://issues.liferay.com/browse/LPS-58403
https://issues.liferay.com/browse/LPS-58408
https://issues.liferay.com/browse/LPS-58416

I sent all of them to revision. Let me know if you have some doubt.

Thank you

cc/ @topolik , @JorgeFerrer

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jcampoy** [comment]
Hey Julio, 
I've just added one commit to this PR.
Sorry by the inconvenience.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/jcampoy/liferay-portal/pull/25. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/e42bbf6~2...e42bbf6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
