### PR TITLE
LPS-59287 Use services instead of SQL in Journal Service Upgrades

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32202. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/51bf938~7...51bf938) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
@epgarcia, creo que falta actualizar lo del portlet preferences, no? He cambiado cositas y arreglado un bug que he visto, que no se pasaba el UUID.

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32264. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/f9ef7b1~7...f9ef7b1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32302. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/14fa33f~7...14fa33f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32311. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/bc1a44b~7...bc1a44b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
