### PR TITLE
Lps 55098 pr 3437 update

### PR DESCRIPTION
**Pull request by arbetts**
@juliocamarero before re-sending this to brian i wanted to see if i was moving in the right direction.

he asked me to make the service API take a Boolean so that we could set it to null explicitly instead of just taking in a true/false parameter and processing it for the Boolean; it looks like this makes the API change a bit more flexible.

In order to make this available in the asset-browser module I need to be able to get a "Boolean" from the request parameters but i could only see a way to get a "boolean". Since we should be able to set listable to null I thought we could use two "boolean" variables from the request; one to see if we want to set it to null and the other to specify the non-null value.

is there a better way to get a "Boolean" from request parameters that allows the default to be "true" but still has the possibility of being set to "null" or "false"?

pr chain:
https://github.com/brianchandotcom/liferay-portal/pull/26879
https://github.com/brianchandotcom/liferay-portal/pull/26937
https://github.com/brianchandotcom/liferay-portal/pull/26955

Please let me know if you would like me to change anything else.

Thanks!
-Andrew

### CODE REVIEW

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
ci:retest

**Comment by arbetts** [comment]
@juliocamarero have you had a chance to review this?

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/27277. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/686604d~1...686604d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
