### PR TITLE
LPS-52763

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @BryanEngler

### CODE REVIEW

**Comment by BryanEngler** [comment]
just a heads up, i never updated the lps but the issue also occurs when assets are sent to the recycle bin, so using the word "Expired" could be misleading... julio i guess you could change the wording to whatever you think is best

**Comment by jonathanmccann** [comment]
@BryanEngler Sorry about that, didn't realize that was a scenario.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey guys, 

can you please have a look at the comments and let me know what you think?

thank you!

**Comment by BryanEngler** [comment]
hey juilo, i dont know if this is too simple of an idea but would renaming the variable to something like "showNonDisplayableAssets" be a possibility?

**Comment by juliocamarero** [comment]
yes, that could work. If we use the field "visible" for that, we could have "showNonVisibleAssets".

**Comment by juliocamarero** [comment]
or actually "includeNonVisibleAssets" since the method is get

**Comment by BryanEngler** [comment]
sounds good. ill look into displaying the status too and send mccann another pr in a little bit.

**Pull request closed without merging**
