### PR TITLE
LPS-67509 Package info

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:stop

**Comment by jkappler** [comment]
cc:/ @pavel-savinov

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Adapted to new repo here: https://github.com/liferay/com-liferay-journal/pull/5

**Pull request closed without merging**
