### PR TITLE
LPS-85021 Avoid NullPointerException

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62758. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/e0afcfdd0291~2...e0afcfdd0291) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62760. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/f99b9fda07d1~3...f99b9fda07d1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
