### PR TITLE
LPS-68061

### PR DESCRIPTION
**Pull request by holatuwol**

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Pull request forwarded to https://github.com/epgarcia/liferay-portal/pull/557. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
