### PR TITLE
LPS-55229 I18n Servlet - Add an option for making enabled/disabled url-patterns

### PR DESCRIPTION
**Pull request by sergiosanchez**

### CODE REVIEW

**Comment by sergiosanchez** [comment]
Hi @juliocamarero This is a request from some customers. They want the portal to return a 404 for the languages that are not available so those URLs so not get indexed by SERPs like Google. So, here is a PR to include a property so the default behaviour of the portal can be changed.
Until now, the only way was to disable the servlet mappings for the undesired languages in web.xml for the I18nServlet.
Thanks.

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26390. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/b542cfb~1...b542cfb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/sergiosanchez/liferay-portal/pull/24. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/b542cfb~1...b542cfb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/26393. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/e5254a5~1...e5254a5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
