### PR TITLE
LPS-63133 Product Menu styles are not loaded on panel page

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
wpid-4000

YEEEEIIIIIIIII

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35963. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/ba61def~1...ba61def) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
![Image of 4000] (http://www.graphene-info.com/files/graphene/Graphene-Info-hits-4000-img_assist-400x383.jpg)

AWESOME!!!!

**Pull request closed without merging**
