### PR TITLE
[TECH-SUPPORT] LPS-54646 Localized URL (ex. /en) are not being mapped accordingly to site available locales

### PR DESCRIPTION
**Pull request by laszlocsontos**
Hi Guys,

@juliocamarero

Let's suppose that we have the following configuration in the portal-ext:
locales.enabled=ca_ES,zh_CN,en_US,fi_FI,fr_FR,de_DE,iw_IL,hu_HU,ja_JP,pt_BR,es_ES,en_GB

With this values, /en will be mapped to en_US.

If a portal administrator creates a site with specific locales (ex. de_DE and en_GB) and then if someone requests a page like "http://localhost:8080/en/PAGE", for this URL, /en will be mapped to en_US, which is a global enabled locale for our portal, but it isn't for this specific site. As a result, we are returning the default locale for the user in hands, which can be German for instance, resulting in a page requested in English and presented in German (when we have en_GB as an enabled locale for this specific site).

@shuyangzhou

While fixing the issue we've discovered that the way LanguageImpl manipulates collections _groupLocalesMap, _groupLocalesSet isn't thread-safe. Adding another collection to next to these seemed to worsen the problem.

What I did was that I encapsulated these three collections into an internal class and used a single ConcurrentHashMap<Long, GroupLocales> to map its instances against groupIds.

What do you think about this approach?
Do you have a better idea in mind to fix this?

Thanks,
László

### CODE REVIEW

**Comment by shuyangzhou** [comment]
hehe, I am not surprised, thread safety issues every where......

@juliocamarero please review @laszlocsontos 's fix's logic first, if you are ok with that, send it to me, I will recheck the thread safety issue.

Thanks guys!

**Comment by laszlocsontos** [comment]
Thanks @shuyangzhou!

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
I will close this pull since @fafonso is probably working on another one.

thanks! :+1:

**Pull request closed without merging**
