### PR TITLE
LPS-85463 Until LPS-85607 is fixed, we need to execute the filter query this way.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63346. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/89cccfcaf10b~1...89cccfcaf10b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
