### PR TITLE
LPS-67751 Guest Can View the Web Content even doesn't have the view permission

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:/ @pavel-savinov

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42826. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/136. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
