### PR TITLE
LPS-63052 SF

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @jbalsas

**Comment by jbalsas** [comment]
LGTM

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/evannagayama/liferay-portal/pull/530. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/evannagayama/liferay-portal/pull/540. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
