### PR TITLE
LPS-85845 Use getDeployment from oauth2-provider-test-util module

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63609. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63621. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/6f2deb687756~1...6f2deb687756) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
