### PR TITLE
LPS-61847 - migrate control-menu styles to theme contributor

### PR DESCRIPTION
**Pull request by jbalsas**
Hey Chema,

Attached are the changes to migrate the control-menu styles to a theme contributor. I included the styles from the control-menu-taglib in 469091c.

Next I'm going to start exploring adding an 'active' state to contributors, and possibly the 'exclusive' vs 'additive' states.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @mjbradford89 ,

due to the latest changes in the control menu, this pull doesn't rebase now :(

The commit that fails is the one that moves the css files... could you please redo that and resend?

thanks a lot!!

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/35114. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/b7a32b6~2...b7a32b6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mjbradford89** [comment]
Hey @juliocamarero, No problem.  Here is the new pull: https://github.com/juliocamarero/liferay-portal/pull/3967.
Please let me know if there are any issues.  Thanks!

**Pull request closed without merging**
