### PR TITLE
[TECHNICAL-SUPPORT] LPS-61570

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @ericyanLr

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hey @jonathanmccann @ericyanLr 

I like your approach, I think the idea is very good to solve the problem. The only think I don't like in this pull is to have the method getRefreshURLParametersJSON in PortletURLUtil. Wouldn't it be possible to just call PortletURLUtil.getRefreshURLParameters() in load_render_portlet.jsp and then when we pass it to the JS function, convert it to JSON using a generic utility that can convert a Map into a JSON object?

Thanks!

**Comment by ericyanLr** [comment]
Hey @juliocamarero,

Thank you for your input, I have found a way to convert the map into a JSON object within load_render_portlet.jsp.  I will be sending another pull request with the changes.

Thanks!

**Comment by juliocamarero** [comment]
Awesome! Thank you!!

**Pull request closed without merging**
