### PR TITLE
[Technical Support] LPS-59252 - Inconsistent locale between URL and page content

### PR DESCRIPTION
**Pull request by zsigmondrab**
Hi Julio,

I am sending this to you as you reviewed the original fix for the problem also. See juliocamarero#3708

This pull request is about extending that fix for handling the url with no group and layout friendly urls in the request uri and the test case.

I have tested all of the aspects, even with different context and proxy path so I can say that this modification should not cause any problem.

I have found only one problem which was a hidden one that occurred only after our fix. That is the third commit about which could be handled with a different LPS also. Please, let me know if we should do so.

Let me know that also if you have any concern.

Thank you,
Zsigmond

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
hey @zsigmondrab, thanks a ton for your help!! 

Regarding the third commit you mention... I only see a test there... did you add another commit somewhere? 

thanks!!

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32207. [See changes here.](https://github.com/juliocamarero/liferay-portal/compare/8212078~1...8212078) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zsigmondrab** [comment]
Hi Julio,

I meant the second one (https://github.com/zsigmondrab/liferay-portal/commit/75a17ff1cd5c580cb6bdbd8138aefb82544884df), actually. I do not know how I could change them, sorry.

Zsigmond

**Comment by juliocamarero** [comment]
ok, thank you! :+1:

**Pull request closed without merging**
