### PR TITLE
LPS-58382 FriendlyURLs for Site Administration so that users can guess urls for faster access

### PR DESCRIPTION
**Pull request by jkappler**
@juliocamarero, we still have the issue when redirecting, when a site is deleted.

### CODE REVIEW

**Comment by jkappler** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30106. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
ci:retest

**Pull request closed without merging**
